// Code generated by ent, DO NOT EDIT.

package printerassoc

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldLTE(FieldID, id))
}

// PrinterID applies equality check predicate on the "printer_id" field. It's identical to PrinterIDEQ.
func PrinterID(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldPrinterID, v))
}

// HostID applies equality check predicate on the "host_id" field. It's identical to HostIDEQ.
func HostID(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldHostID, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldIsDefault, v))
}

// PrinterIDEQ applies the EQ predicate on the "printer_id" field.
func PrinterIDEQ(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldPrinterID, v))
}

// PrinterIDNEQ applies the NEQ predicate on the "printer_id" field.
func PrinterIDNEQ(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNEQ(FieldPrinterID, v))
}

// PrinterIDIn applies the In predicate on the "printer_id" field.
func PrinterIDIn(vs ...uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldIn(FieldPrinterID, vs...))
}

// PrinterIDNotIn applies the NotIn predicate on the "printer_id" field.
func PrinterIDNotIn(vs ...uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNotIn(FieldPrinterID, vs...))
}

// HostIDEQ applies the EQ predicate on the "host_id" field.
func HostIDEQ(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldHostID, v))
}

// HostIDNEQ applies the NEQ predicate on the "host_id" field.
func HostIDNEQ(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNEQ(FieldHostID, v))
}

// HostIDIn applies the In predicate on the "host_id" field.
func HostIDIn(vs ...uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldIn(FieldHostID, vs...))
}

// HostIDNotIn applies the NotIn predicate on the "host_id" field.
func HostIDNotIn(vs ...uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNotIn(FieldHostID, vs...))
}

// HostIDGT applies the GT predicate on the "host_id" field.
func HostIDGT(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldGT(FieldHostID, v))
}

// HostIDGTE applies the GTE predicate on the "host_id" field.
func HostIDGTE(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldGTE(FieldHostID, v))
}

// HostIDLT applies the LT predicate on the "host_id" field.
func HostIDLT(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldLT(FieldHostID, v))
}

// HostIDLTE applies the LTE predicate on the "host_id" field.
func HostIDLTE(v uuid.UUID) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldLTE(FieldHostID, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.FieldNEQ(FieldIsDefault, v))
}

// HasPrinter applies the HasEdge predicate on the "printer" edge.
func HasPrinter() predicate.PrinterAssoc {
	return predicate.PrinterAssoc(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PrinterTable, PrinterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPrinterWith applies the HasEdge predicate on the "printer" edge with a given conditions (other predicates).
func HasPrinterWith(preds ...predicate.Printer) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(func(s *sql.Selector) {
		step := newPrinterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrinterAssoc) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrinterAssoc) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrinterAssoc) predicate.PrinterAssoc {
	return predicate.PrinterAssoc(sql.NotPredicates(p))
}
