// Code generated by ent, DO NOT EDIT.

package modulestatus

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the modulestatus type in the database.
	Label = "module_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHostID holds the string denoting the host_id field in the database.
	FieldHostID = "host_id"
	// FieldModuleID holds the string denoting the module_id field in the database.
	FieldModuleID = "module_id"
	// FieldIsOn holds the string denoting the is_on field in the database.
	FieldIsOn = "is_on"
	// EdgeModule holds the string denoting the module edge name in mutations.
	EdgeModule = "module"
	// Table holds the table name of the modulestatus in the database.
	Table = "module_status"
	// ModuleTable is the table that holds the module relation/edge.
	ModuleTable = "module_status"
	// ModuleInverseTable is the table name for the Module entity.
	// It exists in this package in order to avoid circular dependency with the "module" package.
	ModuleInverseTable = "modules"
	// ModuleColumn is the table column denoting the module relation/edge.
	ModuleColumn = "module_id"
)

// Columns holds all SQL columns for modulestatus fields.
var Columns = []string{
	FieldID,
	FieldHostID,
	FieldModuleID,
	FieldIsOn,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsOn holds the default value on creation for the "is_on" field.
	DefaultIsOn bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ModuleStatus queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHostID orders the results by the host_id field.
func ByHostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostID, opts...).ToFunc()
}

// ByModuleID orders the results by the module_id field.
func ByModuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModuleID, opts...).ToFunc()
}

// ByIsOn orders the results by the is_on field.
func ByIsOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsOn, opts...).ToFunc()
}

// ByModuleField orders the results by module field.
func ByModuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModuleStep(), sql.OrderByField(field, opts...))
	}
}
func newModuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModuleTable, ModuleColumn),
	)
}
