// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/globalsetting"
)

// GlobalSettingCreate is the builder for creating a GlobalSetting entity.
type GlobalSettingCreate struct {
	config
	mutation *GlobalSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *GlobalSettingCreate) SetKey(v string) *GlobalSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *GlobalSettingCreate) SetValue(v string) *GlobalSettingCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *GlobalSettingCreate) SetNillableValue(v *string) *GlobalSettingCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *GlobalSettingCreate) SetDescription(v string) *GlobalSettingCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GlobalSettingCreate) SetNillableDescription(v *string) *GlobalSettingCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *GlobalSettingCreate) SetCategory(v string) *GlobalSettingCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *GlobalSettingCreate) SetNillableCategory(v *string) *GlobalSettingCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GlobalSettingCreate) SetUpdatedAt(v time.Time) *GlobalSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GlobalSettingCreate) SetNillableUpdatedAt(v *time.Time) *GlobalSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GlobalSettingCreate) SetID(v uuid.UUID) *GlobalSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GlobalSettingCreate) SetNillableID(v *uuid.UUID) *GlobalSettingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GlobalSettingMutation object of the builder.
func (_c *GlobalSettingCreate) Mutation() *GlobalSettingMutation {
	return _c.mutation
}

// Save creates the GlobalSetting in the database.
func (_c *GlobalSettingCreate) Save(ctx context.Context) (*GlobalSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GlobalSettingCreate) SaveX(ctx context.Context) *GlobalSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GlobalSettingCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := globalsetting.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := globalsetting.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := globalsetting.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := globalsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := globalsetting.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GlobalSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "GlobalSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := globalsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "GlobalSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "GlobalSetting.value"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "GlobalSetting.description"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "GlobalSetting.category"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GlobalSetting.updated_at"`)}
	}
	return nil
}

func (_c *GlobalSettingCreate) sqlSave(ctx context.Context) (*GlobalSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GlobalSettingCreate) createSpec() (*GlobalSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &GlobalSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(globalsetting.Table, sqlgraph.NewFieldSpec(globalsetting.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(globalsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(globalsetting.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(globalsetting.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(globalsetting.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(globalsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GlobalSetting.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GlobalSettingUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *GlobalSettingCreate) OnConflict(opts ...sql.ConflictOption) *GlobalSettingUpsertOne {
	_c.conflict = opts
	return &GlobalSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GlobalSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GlobalSettingCreate) OnConflictColumns(columns ...string) *GlobalSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GlobalSettingUpsertOne{
		create: _c,
	}
}

type (
	// GlobalSettingUpsertOne is the builder for "upsert"-ing
	//  one GlobalSetting node.
	GlobalSettingUpsertOne struct {
		create *GlobalSettingCreate
	}

	// GlobalSettingUpsert is the "OnConflict" setter.
	GlobalSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *GlobalSettingUpsert) SetKey(v string) *GlobalSettingUpsert {
	u.Set(globalsetting.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *GlobalSettingUpsert) UpdateKey() *GlobalSettingUpsert {
	u.SetExcluded(globalsetting.FieldKey)
	return u
}

// SetValue sets the "value" field.
func (u *GlobalSettingUpsert) SetValue(v string) *GlobalSettingUpsert {
	u.Set(globalsetting.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *GlobalSettingUpsert) UpdateValue() *GlobalSettingUpsert {
	u.SetExcluded(globalsetting.FieldValue)
	return u
}

// SetDescription sets the "description" field.
func (u *GlobalSettingUpsert) SetDescription(v string) *GlobalSettingUpsert {
	u.Set(globalsetting.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GlobalSettingUpsert) UpdateDescription() *GlobalSettingUpsert {
	u.SetExcluded(globalsetting.FieldDescription)
	return u
}

// SetCategory sets the "category" field.
func (u *GlobalSettingUpsert) SetCategory(v string) *GlobalSettingUpsert {
	u.Set(globalsetting.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *GlobalSettingUpsert) UpdateCategory() *GlobalSettingUpsert {
	u.SetExcluded(globalsetting.FieldCategory)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GlobalSettingUpsert) SetUpdatedAt(v time.Time) *GlobalSettingUpsert {
	u.Set(globalsetting.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GlobalSettingUpsert) UpdateUpdatedAt() *GlobalSettingUpsert {
	u.SetExcluded(globalsetting.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GlobalSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(globalsetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GlobalSettingUpsertOne) UpdateNewValues() *GlobalSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(globalsetting.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GlobalSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GlobalSettingUpsertOne) Ignore() *GlobalSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GlobalSettingUpsertOne) DoNothing() *GlobalSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GlobalSettingCreate.OnConflict
// documentation for more info.
func (u *GlobalSettingUpsertOne) Update(set func(*GlobalSettingUpsert)) *GlobalSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GlobalSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *GlobalSettingUpsertOne) SetKey(v string) *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *GlobalSettingUpsertOne) UpdateKey() *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *GlobalSettingUpsertOne) SetValue(v string) *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *GlobalSettingUpsertOne) UpdateValue() *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateValue()
	})
}

// SetDescription sets the "description" field.
func (u *GlobalSettingUpsertOne) SetDescription(v string) *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GlobalSettingUpsertOne) UpdateDescription() *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateDescription()
	})
}

// SetCategory sets the "category" field.
func (u *GlobalSettingUpsertOne) SetCategory(v string) *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *GlobalSettingUpsertOne) UpdateCategory() *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateCategory()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GlobalSettingUpsertOne) SetUpdatedAt(v time.Time) *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GlobalSettingUpsertOne) UpdateUpdatedAt() *GlobalSettingUpsertOne {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GlobalSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GlobalSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GlobalSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GlobalSettingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GlobalSettingUpsertOne.ID is not supported by MySQL driver. Use GlobalSettingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GlobalSettingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GlobalSettingCreateBulk is the builder for creating many GlobalSetting entities in bulk.
type GlobalSettingCreateBulk struct {
	config
	err      error
	builders []*GlobalSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the GlobalSetting entities in the database.
func (_c *GlobalSettingCreateBulk) Save(ctx context.Context) ([]*GlobalSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GlobalSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GlobalSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GlobalSettingCreateBulk) SaveX(ctx context.Context) []*GlobalSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GlobalSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GlobalSettingUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *GlobalSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *GlobalSettingUpsertBulk {
	_c.conflict = opts
	return &GlobalSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GlobalSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GlobalSettingCreateBulk) OnConflictColumns(columns ...string) *GlobalSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GlobalSettingUpsertBulk{
		create: _c,
	}
}

// GlobalSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of GlobalSetting nodes.
type GlobalSettingUpsertBulk struct {
	create *GlobalSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GlobalSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(globalsetting.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GlobalSettingUpsertBulk) UpdateNewValues() *GlobalSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(globalsetting.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GlobalSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GlobalSettingUpsertBulk) Ignore() *GlobalSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GlobalSettingUpsertBulk) DoNothing() *GlobalSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GlobalSettingCreateBulk.OnConflict
// documentation for more info.
func (u *GlobalSettingUpsertBulk) Update(set func(*GlobalSettingUpsert)) *GlobalSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GlobalSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *GlobalSettingUpsertBulk) SetKey(v string) *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *GlobalSettingUpsertBulk) UpdateKey() *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *GlobalSettingUpsertBulk) SetValue(v string) *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *GlobalSettingUpsertBulk) UpdateValue() *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateValue()
	})
}

// SetDescription sets the "description" field.
func (u *GlobalSettingUpsertBulk) SetDescription(v string) *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GlobalSettingUpsertBulk) UpdateDescription() *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateDescription()
	})
}

// SetCategory sets the "category" field.
func (u *GlobalSettingUpsertBulk) SetCategory(v string) *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *GlobalSettingUpsertBulk) UpdateCategory() *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateCategory()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GlobalSettingUpsertBulk) SetUpdatedAt(v time.Time) *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GlobalSettingUpsertBulk) UpdateUpdatedAt() *GlobalSettingUpsertBulk {
	return u.Update(func(s *GlobalSettingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GlobalSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GlobalSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GlobalSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GlobalSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
