// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/agentlog"
	"github.com/nemvince/fog-next/ent/groupmember"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/hostmac"
	"github.com/nemvince/fog-next/ent/image"
	"github.com/nemvince/fog-next/ent/imaginglog"
	"github.com/nemvince/fog-next/ent/inventory"
	"github.com/nemvince/fog-next/ent/pendingmac"
	"github.com/nemvince/fog-next/ent/predicate"
	"github.com/nemvince/fog-next/ent/snapinassoc"
	"github.com/nemvince/fog-next/ent/snapinjob"
	"github.com/nemvince/fog-next/ent/task"
)

// HostQuery is the builder for querying Host entities.
type HostQuery struct {
	config
	ctx                   *QueryContext
	order                 []host.OrderOption
	inters                []Interceptor
	predicates            []predicate.Host
	withImage             *ImageQuery
	withMacs              *HostMACQuery
	withInventory         *InventoryQuery
	withPendingMacs       *PendingMACQuery
	withGroupMembers      *GroupMemberQuery
	withSnapinAssocs      *SnapinAssocQuery
	withTasks             *TaskQuery
	withImagingLogs       *ImagingLogQuery
	withSnapinJobs        *SnapinJobQuery
	withAgentLogs         *AgentLogQuery
	withNamedMacs         map[string]*HostMACQuery
	withNamedPendingMacs  map[string]*PendingMACQuery
	withNamedGroupMembers map[string]*GroupMemberQuery
	withNamedSnapinAssocs map[string]*SnapinAssocQuery
	withNamedTasks        map[string]*TaskQuery
	withNamedImagingLogs  map[string]*ImagingLogQuery
	withNamedSnapinJobs   map[string]*SnapinJobQuery
	withNamedAgentLogs    map[string]*AgentLogQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HostQuery builder.
func (_q *HostQuery) Where(ps ...predicate.Host) *HostQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *HostQuery) Limit(limit int) *HostQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *HostQuery) Offset(offset int) *HostQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *HostQuery) Unique(unique bool) *HostQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *HostQuery) Order(o ...host.OrderOption) *HostQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryImage chains the current query on the "image" edge.
func (_q *HostQuery) QueryImage() *ImageQuery {
	query := (&ImageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(image.Table, image.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, host.ImageTable, host.ImageColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMacs chains the current query on the "macs" edge.
func (_q *HostQuery) QueryMacs() *HostMACQuery {
	query := (&HostMACClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(hostmac.Table, hostmac.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.MacsTable, host.MacsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInventory chains the current query on the "inventory" edge.
func (_q *HostQuery) QueryInventory() *InventoryQuery {
	query := (&InventoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(inventory.Table, inventory.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, host.InventoryTable, host.InventoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPendingMacs chains the current query on the "pending_macs" edge.
func (_q *HostQuery) QueryPendingMacs() *PendingMACQuery {
	query := (&PendingMACClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(pendingmac.Table, pendingmac.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.PendingMacsTable, host.PendingMacsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroupMembers chains the current query on the "group_members" edge.
func (_q *HostQuery) QueryGroupMembers() *GroupMemberQuery {
	query := (&GroupMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(groupmember.Table, groupmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.GroupMembersTable, host.GroupMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySnapinAssocs chains the current query on the "snapin_assocs" edge.
func (_q *HostQuery) QuerySnapinAssocs() *SnapinAssocQuery {
	query := (&SnapinAssocClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(snapinassoc.Table, snapinassoc.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.SnapinAssocsTable, host.SnapinAssocsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (_q *HostQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.TasksTable, host.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryImagingLogs chains the current query on the "imaging_logs" edge.
func (_q *HostQuery) QueryImagingLogs() *ImagingLogQuery {
	query := (&ImagingLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(imaginglog.Table, imaginglog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.ImagingLogsTable, host.ImagingLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySnapinJobs chains the current query on the "snapin_jobs" edge.
func (_q *HostQuery) QuerySnapinJobs() *SnapinJobQuery {
	query := (&SnapinJobClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(snapinjob.Table, snapinjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.SnapinJobsTable, host.SnapinJobsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentLogs chains the current query on the "agent_logs" edge.
func (_q *HostQuery) QueryAgentLogs() *AgentLogQuery {
	query := (&AgentLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(host.Table, host.FieldID, selector),
			sqlgraph.To(agentlog.Table, agentlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, host.AgentLogsTable, host.AgentLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Host entity from the query.
// Returns a *NotFoundError when no Host was found.
func (_q *HostQuery) First(ctx context.Context) (*Host, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{host.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *HostQuery) FirstX(ctx context.Context) *Host {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Host ID from the query.
// Returns a *NotFoundError when no Host ID was found.
func (_q *HostQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{host.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *HostQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Host entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Host entity is found.
// Returns a *NotFoundError when no Host entities are found.
func (_q *HostQuery) Only(ctx context.Context) (*Host, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{host.Label}
	default:
		return nil, &NotSingularError{host.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *HostQuery) OnlyX(ctx context.Context) *Host {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Host ID in the query.
// Returns a *NotSingularError when more than one Host ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *HostQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{host.Label}
	default:
		err = &NotSingularError{host.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *HostQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Hosts.
func (_q *HostQuery) All(ctx context.Context) ([]*Host, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Host, *HostQuery]()
	return withInterceptors[[]*Host](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *HostQuery) AllX(ctx context.Context) []*Host {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Host IDs.
func (_q *HostQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(host.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *HostQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *HostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*HostQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *HostQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *HostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *HostQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *HostQuery) Clone() *HostQuery {
	if _q == nil {
		return nil
	}
	return &HostQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]host.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Host{}, _q.predicates...),
		withImage:        _q.withImage.Clone(),
		withMacs:         _q.withMacs.Clone(),
		withInventory:    _q.withInventory.Clone(),
		withPendingMacs:  _q.withPendingMacs.Clone(),
		withGroupMembers: _q.withGroupMembers.Clone(),
		withSnapinAssocs: _q.withSnapinAssocs.Clone(),
		withTasks:        _q.withTasks.Clone(),
		withImagingLogs:  _q.withImagingLogs.Clone(),
		withSnapinJobs:   _q.withSnapinJobs.Clone(),
		withAgentLogs:    _q.withAgentLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithImage tells the query-builder to eager-load the nodes that are connected to
// the "image" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithImage(opts ...func(*ImageQuery)) *HostQuery {
	query := (&ImageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withImage = query
	return _q
}

// WithMacs tells the query-builder to eager-load the nodes that are connected to
// the "macs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithMacs(opts ...func(*HostMACQuery)) *HostQuery {
	query := (&HostMACClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMacs = query
	return _q
}

// WithInventory tells the query-builder to eager-load the nodes that are connected to
// the "inventory" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithInventory(opts ...func(*InventoryQuery)) *HostQuery {
	query := (&InventoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInventory = query
	return _q
}

// WithPendingMacs tells the query-builder to eager-load the nodes that are connected to
// the "pending_macs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithPendingMacs(opts ...func(*PendingMACQuery)) *HostQuery {
	query := (&PendingMACClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPendingMacs = query
	return _q
}

// WithGroupMembers tells the query-builder to eager-load the nodes that are connected to
// the "group_members" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithGroupMembers(opts ...func(*GroupMemberQuery)) *HostQuery {
	query := (&GroupMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroupMembers = query
	return _q
}

// WithSnapinAssocs tells the query-builder to eager-load the nodes that are connected to
// the "snapin_assocs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithSnapinAssocs(opts ...func(*SnapinAssocQuery)) *HostQuery {
	query := (&SnapinAssocClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapinAssocs = query
	return _q
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithTasks(opts ...func(*TaskQuery)) *HostQuery {
	query := (&TaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTasks = query
	return _q
}

// WithImagingLogs tells the query-builder to eager-load the nodes that are connected to
// the "imaging_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithImagingLogs(opts ...func(*ImagingLogQuery)) *HostQuery {
	query := (&ImagingLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withImagingLogs = query
	return _q
}

// WithSnapinJobs tells the query-builder to eager-load the nodes that are connected to
// the "snapin_jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithSnapinJobs(opts ...func(*SnapinJobQuery)) *HostQuery {
	query := (&SnapinJobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapinJobs = query
	return _q
}

// WithAgentLogs tells the query-builder to eager-load the nodes that are connected to
// the "agent_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithAgentLogs(opts ...func(*AgentLogQuery)) *HostQuery {
	query := (&AgentLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Host.Query().
//		GroupBy(host.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *HostQuery) GroupBy(field string, fields ...string) *HostGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HostGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = host.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name"`
//	}
//
//	client.Host.Query().
//		Select(host.FieldName).
//		Scan(ctx, &v)
func (_q *HostQuery) Select(fields ...string) *HostSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &HostSelect{HostQuery: _q}
	sbuild.label = host.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HostSelect configured with the given aggregations.
func (_q *HostQuery) Aggregate(fns ...AggregateFunc) *HostSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *HostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !host.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *HostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Host, error) {
	var (
		nodes       = []*Host{}
		_spec       = _q.querySpec()
		loadedTypes = [10]bool{
			_q.withImage != nil,
			_q.withMacs != nil,
			_q.withInventory != nil,
			_q.withPendingMacs != nil,
			_q.withGroupMembers != nil,
			_q.withSnapinAssocs != nil,
			_q.withTasks != nil,
			_q.withImagingLogs != nil,
			_q.withSnapinJobs != nil,
			_q.withAgentLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Host).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Host{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withImage; query != nil {
		if err := _q.loadImage(ctx, query, nodes, nil,
			func(n *Host, e *Image) { n.Edges.Image = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMacs; query != nil {
		if err := _q.loadMacs(ctx, query, nodes,
			func(n *Host) { n.Edges.Macs = []*HostMAC{} },
			func(n *Host, e *HostMAC) { n.Edges.Macs = append(n.Edges.Macs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInventory; query != nil {
		if err := _q.loadInventory(ctx, query, nodes, nil,
			func(n *Host, e *Inventory) { n.Edges.Inventory = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPendingMacs; query != nil {
		if err := _q.loadPendingMacs(ctx, query, nodes,
			func(n *Host) { n.Edges.PendingMacs = []*PendingMAC{} },
			func(n *Host, e *PendingMAC) { n.Edges.PendingMacs = append(n.Edges.PendingMacs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroupMembers; query != nil {
		if err := _q.loadGroupMembers(ctx, query, nodes,
			func(n *Host) { n.Edges.GroupMembers = []*GroupMember{} },
			func(n *Host, e *GroupMember) { n.Edges.GroupMembers = append(n.Edges.GroupMembers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSnapinAssocs; query != nil {
		if err := _q.loadSnapinAssocs(ctx, query, nodes,
			func(n *Host) { n.Edges.SnapinAssocs = []*SnapinAssoc{} },
			func(n *Host, e *SnapinAssoc) { n.Edges.SnapinAssocs = append(n.Edges.SnapinAssocs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTasks; query != nil {
		if err := _q.loadTasks(ctx, query, nodes,
			func(n *Host) { n.Edges.Tasks = []*Task{} },
			func(n *Host, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withImagingLogs; query != nil {
		if err := _q.loadImagingLogs(ctx, query, nodes,
			func(n *Host) { n.Edges.ImagingLogs = []*ImagingLog{} },
			func(n *Host, e *ImagingLog) { n.Edges.ImagingLogs = append(n.Edges.ImagingLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSnapinJobs; query != nil {
		if err := _q.loadSnapinJobs(ctx, query, nodes,
			func(n *Host) { n.Edges.SnapinJobs = []*SnapinJob{} },
			func(n *Host, e *SnapinJob) { n.Edges.SnapinJobs = append(n.Edges.SnapinJobs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentLogs; query != nil {
		if err := _q.loadAgentLogs(ctx, query, nodes,
			func(n *Host) { n.Edges.AgentLogs = []*AgentLog{} },
			func(n *Host, e *AgentLog) { n.Edges.AgentLogs = append(n.Edges.AgentLogs, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedMacs {
		if err := _q.loadMacs(ctx, query, nodes,
			func(n *Host) { n.appendNamedMacs(name) },
			func(n *Host, e *HostMAC) { n.appendNamedMacs(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedPendingMacs {
		if err := _q.loadPendingMacs(ctx, query, nodes,
			func(n *Host) { n.appendNamedPendingMacs(name) },
			func(n *Host, e *PendingMAC) { n.appendNamedPendingMacs(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedGroupMembers {
		if err := _q.loadGroupMembers(ctx, query, nodes,
			func(n *Host) { n.appendNamedGroupMembers(name) },
			func(n *Host, e *GroupMember) { n.appendNamedGroupMembers(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedSnapinAssocs {
		if err := _q.loadSnapinAssocs(ctx, query, nodes,
			func(n *Host) { n.appendNamedSnapinAssocs(name) },
			func(n *Host, e *SnapinAssoc) { n.appendNamedSnapinAssocs(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedTasks {
		if err := _q.loadTasks(ctx, query, nodes,
			func(n *Host) { n.appendNamedTasks(name) },
			func(n *Host, e *Task) { n.appendNamedTasks(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedImagingLogs {
		if err := _q.loadImagingLogs(ctx, query, nodes,
			func(n *Host) { n.appendNamedImagingLogs(name) },
			func(n *Host, e *ImagingLog) { n.appendNamedImagingLogs(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedSnapinJobs {
		if err := _q.loadSnapinJobs(ctx, query, nodes,
			func(n *Host) { n.appendNamedSnapinJobs(name) },
			func(n *Host, e *SnapinJob) { n.appendNamedSnapinJobs(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedAgentLogs {
		if err := _q.loadAgentLogs(ctx, query, nodes,
			func(n *Host) { n.appendNamedAgentLogs(name) },
			func(n *Host, e *AgentLog) { n.appendNamedAgentLogs(name, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *HostQuery) loadImage(ctx context.Context, query *ImageQuery, nodes []*Host, init func(*Host), assign func(*Host, *Image)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Host)
	for i := range nodes {
		if nodes[i].ImageID == nil {
			continue
		}
		fk := *nodes[i].ImageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(image.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "image_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *HostQuery) loadMacs(ctx context.Context, query *HostMACQuery, nodes []*Host, init func(*Host), assign func(*Host, *HostMAC)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hostmac.FieldHostID)
	}
	query.Where(predicate.HostMAC(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.MacsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadInventory(ctx context.Context, query *InventoryQuery, nodes []*Host, init func(*Host), assign func(*Host, *Inventory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(inventory.FieldHostID)
	}
	query.Where(predicate.Inventory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.InventoryColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadPendingMacs(ctx context.Context, query *PendingMACQuery, nodes []*Host, init func(*Host), assign func(*Host, *PendingMAC)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(pendingmac.FieldHostID)
	}
	query.Where(predicate.PendingMAC(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.PendingMacsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		if fk == nil {
			return fmt.Errorf(`foreign-key "host_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadGroupMembers(ctx context.Context, query *GroupMemberQuery, nodes []*Host, init func(*Host), assign func(*Host, *GroupMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(groupmember.FieldHostID)
	}
	query.Where(predicate.GroupMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.GroupMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadSnapinAssocs(ctx context.Context, query *SnapinAssocQuery, nodes []*Host, init func(*Host), assign func(*Host, *SnapinAssoc)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(snapinassoc.FieldHostID)
	}
	query.Where(predicate.SnapinAssoc(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.SnapinAssocsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*Host, init func(*Host), assign func(*Host, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(task.FieldHostID)
	}
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadImagingLogs(ctx context.Context, query *ImagingLogQuery, nodes []*Host, init func(*Host), assign func(*Host, *ImagingLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(imaginglog.FieldHostID)
	}
	query.Where(predicate.ImagingLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.ImagingLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadSnapinJobs(ctx context.Context, query *SnapinJobQuery, nodes []*Host, init func(*Host), assign func(*Host, *SnapinJob)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(snapinjob.FieldHostID)
	}
	query.Where(predicate.SnapinJob(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.SnapinJobsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *HostQuery) loadAgentLogs(ctx context.Context, query *AgentLogQuery, nodes []*Host, init func(*Host), assign func(*Host, *AgentLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Host)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentlog.FieldHostID)
	}
	query.Where(predicate.AgentLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(host.AgentLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.HostID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "host_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *HostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *HostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(host.Table, host.Columns, sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, host.FieldID)
		for i := range fields {
			if fields[i] != host.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withImage != nil {
			_spec.Node.AddColumnOnce(host.FieldImageID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *HostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(host.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = host.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedMacs tells the query-builder to eager-load the nodes that are connected to the "macs"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedMacs(name string, opts ...func(*HostMACQuery)) *HostQuery {
	query := (&HostMACClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedMacs == nil {
		_q.withNamedMacs = make(map[string]*HostMACQuery)
	}
	_q.withNamedMacs[name] = query
	return _q
}

// WithNamedPendingMacs tells the query-builder to eager-load the nodes that are connected to the "pending_macs"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedPendingMacs(name string, opts ...func(*PendingMACQuery)) *HostQuery {
	query := (&PendingMACClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedPendingMacs == nil {
		_q.withNamedPendingMacs = make(map[string]*PendingMACQuery)
	}
	_q.withNamedPendingMacs[name] = query
	return _q
}

// WithNamedGroupMembers tells the query-builder to eager-load the nodes that are connected to the "group_members"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedGroupMembers(name string, opts ...func(*GroupMemberQuery)) *HostQuery {
	query := (&GroupMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedGroupMembers == nil {
		_q.withNamedGroupMembers = make(map[string]*GroupMemberQuery)
	}
	_q.withNamedGroupMembers[name] = query
	return _q
}

// WithNamedSnapinAssocs tells the query-builder to eager-load the nodes that are connected to the "snapin_assocs"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedSnapinAssocs(name string, opts ...func(*SnapinAssocQuery)) *HostQuery {
	query := (&SnapinAssocClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedSnapinAssocs == nil {
		_q.withNamedSnapinAssocs = make(map[string]*SnapinAssocQuery)
	}
	_q.withNamedSnapinAssocs[name] = query
	return _q
}

// WithNamedTasks tells the query-builder to eager-load the nodes that are connected to the "tasks"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedTasks(name string, opts ...func(*TaskQuery)) *HostQuery {
	query := (&TaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedTasks == nil {
		_q.withNamedTasks = make(map[string]*TaskQuery)
	}
	_q.withNamedTasks[name] = query
	return _q
}

// WithNamedImagingLogs tells the query-builder to eager-load the nodes that are connected to the "imaging_logs"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedImagingLogs(name string, opts ...func(*ImagingLogQuery)) *HostQuery {
	query := (&ImagingLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedImagingLogs == nil {
		_q.withNamedImagingLogs = make(map[string]*ImagingLogQuery)
	}
	_q.withNamedImagingLogs[name] = query
	return _q
}

// WithNamedSnapinJobs tells the query-builder to eager-load the nodes that are connected to the "snapin_jobs"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedSnapinJobs(name string, opts ...func(*SnapinJobQuery)) *HostQuery {
	query := (&SnapinJobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedSnapinJobs == nil {
		_q.withNamedSnapinJobs = make(map[string]*SnapinJobQuery)
	}
	_q.withNamedSnapinJobs[name] = query
	return _q
}

// WithNamedAgentLogs tells the query-builder to eager-load the nodes that are connected to the "agent_logs"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *HostQuery) WithNamedAgentLogs(name string, opts ...func(*AgentLogQuery)) *HostQuery {
	query := (&AgentLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedAgentLogs == nil {
		_q.withNamedAgentLogs = make(map[string]*AgentLogQuery)
	}
	_q.withNamedAgentLogs[name] = query
	return _q
}

// HostGroupBy is the group-by builder for Host entities.
type HostGroupBy struct {
	selector
	build *HostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *HostGroupBy) Aggregate(fns ...AggregateFunc) *HostGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *HostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HostQuery, *HostGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *HostGroupBy) sqlScan(ctx context.Context, root *HostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HostSelect is the builder for selecting fields of Host entities.
type HostSelect struct {
	*HostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *HostSelect) Aggregate(fns ...AggregateFunc) *HostSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *HostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HostQuery, *HostSelect](ctx, _s.HostQuery, _s, _s.inters, v)
}

func (_s *HostSelect) sqlScan(ctx context.Context, root *HostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
