// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/hostmac"
)

// HostMACCreate is the builder for creating a HostMAC entity.
type HostMACCreate struct {
	config
	mutation *HostMACMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHostID sets the "host_id" field.
func (_c *HostMACCreate) SetHostID(v uuid.UUID) *HostMACCreate {
	_c.mutation.SetHostID(v)
	return _c
}

// SetMAC sets the "mac" field.
func (_c *HostMACCreate) SetMAC(v string) *HostMACCreate {
	_c.mutation.SetMAC(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *HostMACCreate) SetDescription(v string) *HostMACCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *HostMACCreate) SetNillableDescription(v *string) *HostMACCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsPrimary sets the "is_primary" field.
func (_c *HostMACCreate) SetIsPrimary(v bool) *HostMACCreate {
	_c.mutation.SetIsPrimary(v)
	return _c
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_c *HostMACCreate) SetNillableIsPrimary(v *bool) *HostMACCreate {
	if v != nil {
		_c.SetIsPrimary(*v)
	}
	return _c
}

// SetIsIgnored sets the "is_ignored" field.
func (_c *HostMACCreate) SetIsIgnored(v bool) *HostMACCreate {
	_c.mutation.SetIsIgnored(v)
	return _c
}

// SetNillableIsIgnored sets the "is_ignored" field if the given value is not nil.
func (_c *HostMACCreate) SetNillableIsIgnored(v *bool) *HostMACCreate {
	if v != nil {
		_c.SetIsIgnored(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HostMACCreate) SetCreatedAt(v time.Time) *HostMACCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HostMACCreate) SetNillableCreatedAt(v *time.Time) *HostMACCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HostMACCreate) SetID(v uuid.UUID) *HostMACCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HostMACCreate) SetNillableID(v *uuid.UUID) *HostMACCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetHost sets the "host" edge to the Host entity.
func (_c *HostMACCreate) SetHost(v *Host) *HostMACCreate {
	return _c.SetHostID(v.ID)
}

// Mutation returns the HostMACMutation object of the builder.
func (_c *HostMACCreate) Mutation() *HostMACMutation {
	return _c.mutation
}

// Save creates the HostMAC in the database.
func (_c *HostMACCreate) Save(ctx context.Context) (*HostMAC, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HostMACCreate) SaveX(ctx context.Context) *HostMAC {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostMACCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostMACCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HostMACCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := hostmac.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		v := hostmac.DefaultIsPrimary
		_c.mutation.SetIsPrimary(v)
	}
	if _, ok := _c.mutation.IsIgnored(); !ok {
		v := hostmac.DefaultIsIgnored
		_c.mutation.SetIsIgnored(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := hostmac.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := hostmac.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HostMACCreate) check() error {
	if _, ok := _c.mutation.HostID(); !ok {
		return &ValidationError{Name: "host_id", err: errors.New(`ent: missing required field "HostMAC.host_id"`)}
	}
	if _, ok := _c.mutation.MAC(); !ok {
		return &ValidationError{Name: "mac", err: errors.New(`ent: missing required field "HostMAC.mac"`)}
	}
	if v, ok := _c.mutation.MAC(); ok {
		if err := hostmac.MACValidator(v); err != nil {
			return &ValidationError{Name: "mac", err: fmt.Errorf(`ent: validator failed for field "HostMAC.mac": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "HostMAC.description"`)}
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		return &ValidationError{Name: "is_primary", err: errors.New(`ent: missing required field "HostMAC.is_primary"`)}
	}
	if _, ok := _c.mutation.IsIgnored(); !ok {
		return &ValidationError{Name: "is_ignored", err: errors.New(`ent: missing required field "HostMAC.is_ignored"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HostMAC.created_at"`)}
	}
	if len(_c.mutation.HostIDs()) == 0 {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required edge "HostMAC.host"`)}
	}
	return nil
}

func (_c *HostMACCreate) sqlSave(ctx context.Context) (*HostMAC, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HostMACCreate) createSpec() (*HostMAC, *sqlgraph.CreateSpec) {
	var (
		_node = &HostMAC{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hostmac.Table, sqlgraph.NewFieldSpec(hostmac.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MAC(); ok {
		_spec.SetField(hostmac.FieldMAC, field.TypeString, value)
		_node.MAC = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(hostmac.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsPrimary(); ok {
		_spec.SetField(hostmac.FieldIsPrimary, field.TypeBool, value)
		_node.IsPrimary = value
	}
	if value, ok := _c.mutation.IsIgnored(); ok {
		_spec.SetField(hostmac.FieldIsIgnored, field.TypeBool, value)
		_node.IsIgnored = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hostmac.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hostmac.HostTable,
			Columns: []string{hostmac.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HostMAC.Create().
//		SetHostID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HostMACUpsert) {
//			SetHostID(v+v).
//		}).
//		Exec(ctx)
func (_c *HostMACCreate) OnConflict(opts ...sql.ConflictOption) *HostMACUpsertOne {
	_c.conflict = opts
	return &HostMACUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HostMAC.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HostMACCreate) OnConflictColumns(columns ...string) *HostMACUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HostMACUpsertOne{
		create: _c,
	}
}

type (
	// HostMACUpsertOne is the builder for "upsert"-ing
	//  one HostMAC node.
	HostMACUpsertOne struct {
		create *HostMACCreate
	}

	// HostMACUpsert is the "OnConflict" setter.
	HostMACUpsert struct {
		*sql.UpdateSet
	}
)

// SetHostID sets the "host_id" field.
func (u *HostMACUpsert) SetHostID(v uuid.UUID) *HostMACUpsert {
	u.Set(hostmac.FieldHostID, v)
	return u
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *HostMACUpsert) UpdateHostID() *HostMACUpsert {
	u.SetExcluded(hostmac.FieldHostID)
	return u
}

// SetMAC sets the "mac" field.
func (u *HostMACUpsert) SetMAC(v string) *HostMACUpsert {
	u.Set(hostmac.FieldMAC, v)
	return u
}

// UpdateMAC sets the "mac" field to the value that was provided on create.
func (u *HostMACUpsert) UpdateMAC() *HostMACUpsert {
	u.SetExcluded(hostmac.FieldMAC)
	return u
}

// SetDescription sets the "description" field.
func (u *HostMACUpsert) SetDescription(v string) *HostMACUpsert {
	u.Set(hostmac.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HostMACUpsert) UpdateDescription() *HostMACUpsert {
	u.SetExcluded(hostmac.FieldDescription)
	return u
}

// SetIsPrimary sets the "is_primary" field.
func (u *HostMACUpsert) SetIsPrimary(v bool) *HostMACUpsert {
	u.Set(hostmac.FieldIsPrimary, v)
	return u
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *HostMACUpsert) UpdateIsPrimary() *HostMACUpsert {
	u.SetExcluded(hostmac.FieldIsPrimary)
	return u
}

// SetIsIgnored sets the "is_ignored" field.
func (u *HostMACUpsert) SetIsIgnored(v bool) *HostMACUpsert {
	u.Set(hostmac.FieldIsIgnored, v)
	return u
}

// UpdateIsIgnored sets the "is_ignored" field to the value that was provided on create.
func (u *HostMACUpsert) UpdateIsIgnored() *HostMACUpsert {
	u.SetExcluded(hostmac.FieldIsIgnored)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.HostMAC.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hostmac.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HostMACUpsertOne) UpdateNewValues() *HostMACUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(hostmac.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hostmac.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HostMAC.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HostMACUpsertOne) Ignore() *HostMACUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HostMACUpsertOne) DoNothing() *HostMACUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HostMACCreate.OnConflict
// documentation for more info.
func (u *HostMACUpsertOne) Update(set func(*HostMACUpsert)) *HostMACUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HostMACUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostID sets the "host_id" field.
func (u *HostMACUpsertOne) SetHostID(v uuid.UUID) *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *HostMACUpsertOne) UpdateHostID() *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateHostID()
	})
}

// SetMAC sets the "mac" field.
func (u *HostMACUpsertOne) SetMAC(v string) *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.SetMAC(v)
	})
}

// UpdateMAC sets the "mac" field to the value that was provided on create.
func (u *HostMACUpsertOne) UpdateMAC() *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateMAC()
	})
}

// SetDescription sets the "description" field.
func (u *HostMACUpsertOne) SetDescription(v string) *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HostMACUpsertOne) UpdateDescription() *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateDescription()
	})
}

// SetIsPrimary sets the "is_primary" field.
func (u *HostMACUpsertOne) SetIsPrimary(v bool) *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.SetIsPrimary(v)
	})
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *HostMACUpsertOne) UpdateIsPrimary() *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateIsPrimary()
	})
}

// SetIsIgnored sets the "is_ignored" field.
func (u *HostMACUpsertOne) SetIsIgnored(v bool) *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.SetIsIgnored(v)
	})
}

// UpdateIsIgnored sets the "is_ignored" field to the value that was provided on create.
func (u *HostMACUpsertOne) UpdateIsIgnored() *HostMACUpsertOne {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateIsIgnored()
	})
}

// Exec executes the query.
func (u *HostMACUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HostMACCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HostMACUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HostMACUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HostMACUpsertOne.ID is not supported by MySQL driver. Use HostMACUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HostMACUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HostMACCreateBulk is the builder for creating many HostMAC entities in bulk.
type HostMACCreateBulk struct {
	config
	err      error
	builders []*HostMACCreate
	conflict []sql.ConflictOption
}

// Save creates the HostMAC entities in the database.
func (_c *HostMACCreateBulk) Save(ctx context.Context) ([]*HostMAC, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HostMAC, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HostMACMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HostMACCreateBulk) SaveX(ctx context.Context) []*HostMAC {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HostMACCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HostMACCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HostMAC.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HostMACUpsert) {
//			SetHostID(v+v).
//		}).
//		Exec(ctx)
func (_c *HostMACCreateBulk) OnConflict(opts ...sql.ConflictOption) *HostMACUpsertBulk {
	_c.conflict = opts
	return &HostMACUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HostMAC.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HostMACCreateBulk) OnConflictColumns(columns ...string) *HostMACUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HostMACUpsertBulk{
		create: _c,
	}
}

// HostMACUpsertBulk is the builder for "upsert"-ing
// a bulk of HostMAC nodes.
type HostMACUpsertBulk struct {
	create *HostMACCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HostMAC.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hostmac.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HostMACUpsertBulk) UpdateNewValues() *HostMACUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(hostmac.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hostmac.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HostMAC.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HostMACUpsertBulk) Ignore() *HostMACUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HostMACUpsertBulk) DoNothing() *HostMACUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HostMACCreateBulk.OnConflict
// documentation for more info.
func (u *HostMACUpsertBulk) Update(set func(*HostMACUpsert)) *HostMACUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HostMACUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostID sets the "host_id" field.
func (u *HostMACUpsertBulk) SetHostID(v uuid.UUID) *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *HostMACUpsertBulk) UpdateHostID() *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateHostID()
	})
}

// SetMAC sets the "mac" field.
func (u *HostMACUpsertBulk) SetMAC(v string) *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.SetMAC(v)
	})
}

// UpdateMAC sets the "mac" field to the value that was provided on create.
func (u *HostMACUpsertBulk) UpdateMAC() *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateMAC()
	})
}

// SetDescription sets the "description" field.
func (u *HostMACUpsertBulk) SetDescription(v string) *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HostMACUpsertBulk) UpdateDescription() *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateDescription()
	})
}

// SetIsPrimary sets the "is_primary" field.
func (u *HostMACUpsertBulk) SetIsPrimary(v bool) *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.SetIsPrimary(v)
	})
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *HostMACUpsertBulk) UpdateIsPrimary() *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateIsPrimary()
	})
}

// SetIsIgnored sets the "is_ignored" field.
func (u *HostMACUpsertBulk) SetIsIgnored(v bool) *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.SetIsIgnored(v)
	})
}

// UpdateIsIgnored sets the "is_ignored" field to the value that was provided on create.
func (u *HostMACUpsertBulk) UpdateIsIgnored() *HostMACUpsertBulk {
	return u.Update(func(s *HostMACUpsert) {
		s.UpdateIsIgnored()
	})
}

// Exec executes the query.
func (u *HostMACUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HostMACCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HostMACCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HostMACUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
