// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/hostmac"
	"github.com/nemvince/fog-next/ent/predicate"
)

// HostMACUpdate is the builder for updating HostMAC entities.
type HostMACUpdate struct {
	config
	hooks    []Hook
	mutation *HostMACMutation
}

// Where appends a list predicates to the HostMACUpdate builder.
func (_u *HostMACUpdate) Where(ps ...predicate.HostMAC) *HostMACUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHostID sets the "host_id" field.
func (_u *HostMACUpdate) SetHostID(v uuid.UUID) *HostMACUpdate {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *HostMACUpdate) SetNillableHostID(v *uuid.UUID) *HostMACUpdate {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetMAC sets the "mac" field.
func (_u *HostMACUpdate) SetMAC(v string) *HostMACUpdate {
	_u.mutation.SetMAC(v)
	return _u
}

// SetNillableMAC sets the "mac" field if the given value is not nil.
func (_u *HostMACUpdate) SetNillableMAC(v *string) *HostMACUpdate {
	if v != nil {
		_u.SetMAC(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HostMACUpdate) SetDescription(v string) *HostMACUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HostMACUpdate) SetNillableDescription(v *string) *HostMACUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *HostMACUpdate) SetIsPrimary(v bool) *HostMACUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *HostMACUpdate) SetNillableIsPrimary(v *bool) *HostMACUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetIsIgnored sets the "is_ignored" field.
func (_u *HostMACUpdate) SetIsIgnored(v bool) *HostMACUpdate {
	_u.mutation.SetIsIgnored(v)
	return _u
}

// SetNillableIsIgnored sets the "is_ignored" field if the given value is not nil.
func (_u *HostMACUpdate) SetNillableIsIgnored(v *bool) *HostMACUpdate {
	if v != nil {
		_u.SetIsIgnored(*v)
	}
	return _u
}

// SetHost sets the "host" edge to the Host entity.
func (_u *HostMACUpdate) SetHost(v *Host) *HostMACUpdate {
	return _u.SetHostID(v.ID)
}

// Mutation returns the HostMACMutation object of the builder.
func (_u *HostMACUpdate) Mutation() *HostMACMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the Host entity.
func (_u *HostMACUpdate) ClearHost() *HostMACUpdate {
	_u.mutation.ClearHost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HostMACUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HostMACUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HostMACUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HostMACUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HostMACUpdate) check() error {
	if v, ok := _u.mutation.MAC(); ok {
		if err := hostmac.MACValidator(v); err != nil {
			return &ValidationError{Name: "mac", err: fmt.Errorf(`ent: validator failed for field "HostMAC.mac": %w`, err)}
		}
	}
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HostMAC.host"`)
	}
	return nil
}

func (_u *HostMACUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hostmac.Table, hostmac.Columns, sqlgraph.NewFieldSpec(hostmac.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MAC(); ok {
		_spec.SetField(hostmac.FieldMAC, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hostmac.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(hostmac.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsIgnored(); ok {
		_spec.SetField(hostmac.FieldIsIgnored, field.TypeBool, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hostmac.HostTable,
			Columns: []string{hostmac.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hostmac.HostTable,
			Columns: []string{hostmac.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hostmac.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HostMACUpdateOne is the builder for updating a single HostMAC entity.
type HostMACUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HostMACMutation
}

// SetHostID sets the "host_id" field.
func (_u *HostMACUpdateOne) SetHostID(v uuid.UUID) *HostMACUpdateOne {
	_u.mutation.SetHostID(v)
	return _u
}

// SetNillableHostID sets the "host_id" field if the given value is not nil.
func (_u *HostMACUpdateOne) SetNillableHostID(v *uuid.UUID) *HostMACUpdateOne {
	if v != nil {
		_u.SetHostID(*v)
	}
	return _u
}

// SetMAC sets the "mac" field.
func (_u *HostMACUpdateOne) SetMAC(v string) *HostMACUpdateOne {
	_u.mutation.SetMAC(v)
	return _u
}

// SetNillableMAC sets the "mac" field if the given value is not nil.
func (_u *HostMACUpdateOne) SetNillableMAC(v *string) *HostMACUpdateOne {
	if v != nil {
		_u.SetMAC(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HostMACUpdateOne) SetDescription(v string) *HostMACUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HostMACUpdateOne) SetNillableDescription(v *string) *HostMACUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *HostMACUpdateOne) SetIsPrimary(v bool) *HostMACUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *HostMACUpdateOne) SetNillableIsPrimary(v *bool) *HostMACUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetIsIgnored sets the "is_ignored" field.
func (_u *HostMACUpdateOne) SetIsIgnored(v bool) *HostMACUpdateOne {
	_u.mutation.SetIsIgnored(v)
	return _u
}

// SetNillableIsIgnored sets the "is_ignored" field if the given value is not nil.
func (_u *HostMACUpdateOne) SetNillableIsIgnored(v *bool) *HostMACUpdateOne {
	if v != nil {
		_u.SetIsIgnored(*v)
	}
	return _u
}

// SetHost sets the "host" edge to the Host entity.
func (_u *HostMACUpdateOne) SetHost(v *Host) *HostMACUpdateOne {
	return _u.SetHostID(v.ID)
}

// Mutation returns the HostMACMutation object of the builder.
func (_u *HostMACUpdateOne) Mutation() *HostMACMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the Host entity.
func (_u *HostMACUpdateOne) ClearHost() *HostMACUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// Where appends a list predicates to the HostMACUpdate builder.
func (_u *HostMACUpdateOne) Where(ps ...predicate.HostMAC) *HostMACUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HostMACUpdateOne) Select(field string, fields ...string) *HostMACUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HostMAC entity.
func (_u *HostMACUpdateOne) Save(ctx context.Context) (*HostMAC, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HostMACUpdateOne) SaveX(ctx context.Context) *HostMAC {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HostMACUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HostMACUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HostMACUpdateOne) check() error {
	if v, ok := _u.mutation.MAC(); ok {
		if err := hostmac.MACValidator(v); err != nil {
			return &ValidationError{Name: "mac", err: fmt.Errorf(`ent: validator failed for field "HostMAC.mac": %w`, err)}
		}
	}
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HostMAC.host"`)
	}
	return nil
}

func (_u *HostMACUpdateOne) sqlSave(ctx context.Context) (_node *HostMAC, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hostmac.Table, hostmac.Columns, sqlgraph.NewFieldSpec(hostmac.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HostMAC.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hostmac.FieldID)
		for _, f := range fields {
			if !hostmac.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hostmac.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MAC(); ok {
		_spec.SetField(hostmac.FieldMAC, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(hostmac.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(hostmac.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsIgnored(); ok {
		_spec.SetField(hostmac.FieldIsIgnored, field.TypeBool, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hostmac.HostTable,
			Columns: []string{hostmac.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hostmac.HostTable,
			Columns: []string{hostmac.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HostMAC{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hostmac.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
