// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/inventory"
)

// InventoryCreate is the builder for creating a Inventory entity.
type InventoryCreate struct {
	config
	mutation *InventoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHostID sets the "host_id" field.
func (_c *InventoryCreate) SetHostID(v uuid.UUID) *InventoryCreate {
	_c.mutation.SetHostID(v)
	return _c
}

// SetCPUModel sets the "cpu_model" field.
func (_c *InventoryCreate) SetCPUModel(v string) *InventoryCreate {
	_c.mutation.SetCPUModel(v)
	return _c
}

// SetNillableCPUModel sets the "cpu_model" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableCPUModel(v *string) *InventoryCreate {
	if v != nil {
		_c.SetCPUModel(*v)
	}
	return _c
}

// SetCPUCores sets the "cpu_cores" field.
func (_c *InventoryCreate) SetCPUCores(v int) *InventoryCreate {
	_c.mutation.SetCPUCores(v)
	return _c
}

// SetNillableCPUCores sets the "cpu_cores" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableCPUCores(v *int) *InventoryCreate {
	if v != nil {
		_c.SetCPUCores(*v)
	}
	return _c
}

// SetCPUFreqMhz sets the "cpu_freq_mhz" field.
func (_c *InventoryCreate) SetCPUFreqMhz(v int) *InventoryCreate {
	_c.mutation.SetCPUFreqMhz(v)
	return _c
}

// SetNillableCPUFreqMhz sets the "cpu_freq_mhz" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableCPUFreqMhz(v *int) *InventoryCreate {
	if v != nil {
		_c.SetCPUFreqMhz(*v)
	}
	return _c
}

// SetRAMMib sets the "ram_mib" field.
func (_c *InventoryCreate) SetRAMMib(v int) *InventoryCreate {
	_c.mutation.SetRAMMib(v)
	return _c
}

// SetNillableRAMMib sets the "ram_mib" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableRAMMib(v *int) *InventoryCreate {
	if v != nil {
		_c.SetRAMMib(*v)
	}
	return _c
}

// SetHdModel sets the "hd_model" field.
func (_c *InventoryCreate) SetHdModel(v string) *InventoryCreate {
	_c.mutation.SetHdModel(v)
	return _c
}

// SetNillableHdModel sets the "hd_model" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableHdModel(v *string) *InventoryCreate {
	if v != nil {
		_c.SetHdModel(*v)
	}
	return _c
}

// SetHdSizeGB sets the "hd_size_gb" field.
func (_c *InventoryCreate) SetHdSizeGB(v int) *InventoryCreate {
	_c.mutation.SetHdSizeGB(v)
	return _c
}

// SetNillableHdSizeGB sets the "hd_size_gb" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableHdSizeGB(v *int) *InventoryCreate {
	if v != nil {
		_c.SetHdSizeGB(*v)
	}
	return _c
}

// SetManufacturer sets the "manufacturer" field.
func (_c *InventoryCreate) SetManufacturer(v string) *InventoryCreate {
	_c.mutation.SetManufacturer(v)
	return _c
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableManufacturer(v *string) *InventoryCreate {
	if v != nil {
		_c.SetManufacturer(*v)
	}
	return _c
}

// SetProduct sets the "product" field.
func (_c *InventoryCreate) SetProduct(v string) *InventoryCreate {
	_c.mutation.SetProduct(v)
	return _c
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableProduct(v *string) *InventoryCreate {
	if v != nil {
		_c.SetProduct(*v)
	}
	return _c
}

// SetSerial sets the "serial" field.
func (_c *InventoryCreate) SetSerial(v string) *InventoryCreate {
	_c.mutation.SetSerial(v)
	return _c
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableSerial(v *string) *InventoryCreate {
	if v != nil {
		_c.SetSerial(*v)
	}
	return _c
}

// SetUUID sets the "uuid" field.
func (_c *InventoryCreate) SetUUID(v string) *InventoryCreate {
	_c.mutation.SetUUID(v)
	return _c
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableUUID(v *string) *InventoryCreate {
	if v != nil {
		_c.SetUUID(*v)
	}
	return _c
}

// SetBiosVersion sets the "bios_version" field.
func (_c *InventoryCreate) SetBiosVersion(v string) *InventoryCreate {
	_c.mutation.SetBiosVersion(v)
	return _c
}

// SetNillableBiosVersion sets the "bios_version" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableBiosVersion(v *string) *InventoryCreate {
	if v != nil {
		_c.SetBiosVersion(*v)
	}
	return _c
}

// SetPrimaryMAC sets the "primary_mac" field.
func (_c *InventoryCreate) SetPrimaryMAC(v string) *InventoryCreate {
	_c.mutation.SetPrimaryMAC(v)
	return _c
}

// SetNillablePrimaryMAC sets the "primary_mac" field if the given value is not nil.
func (_c *InventoryCreate) SetNillablePrimaryMAC(v *string) *InventoryCreate {
	if v != nil {
		_c.SetPrimaryMAC(*v)
	}
	return _c
}

// SetOsName sets the "os_name" field.
func (_c *InventoryCreate) SetOsName(v string) *InventoryCreate {
	_c.mutation.SetOsName(v)
	return _c
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableOsName(v *string) *InventoryCreate {
	if v != nil {
		_c.SetOsName(*v)
	}
	return _c
}

// SetOsVersion sets the "os_version" field.
func (_c *InventoryCreate) SetOsVersion(v string) *InventoryCreate {
	_c.mutation.SetOsVersion(v)
	return _c
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableOsVersion(v *string) *InventoryCreate {
	if v != nil {
		_c.SetOsVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InventoryCreate) SetCreatedAt(v time.Time) *InventoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableCreatedAt(v *time.Time) *InventoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InventoryCreate) SetUpdatedAt(v time.Time) *InventoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableUpdatedAt(v *time.Time) *InventoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InventoryCreate) SetID(v uuid.UUID) *InventoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableID(v *uuid.UUID) *InventoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetHost sets the "host" edge to the Host entity.
func (_c *InventoryCreate) SetHost(v *Host) *InventoryCreate {
	return _c.SetHostID(v.ID)
}

// Mutation returns the InventoryMutation object of the builder.
func (_c *InventoryCreate) Mutation() *InventoryMutation {
	return _c.mutation
}

// Save creates the Inventory in the database.
func (_c *InventoryCreate) Save(ctx context.Context) (*Inventory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryCreate) SaveX(ctx context.Context) *Inventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventoryCreate) defaults() {
	if _, ok := _c.mutation.CPUModel(); !ok {
		v := inventory.DefaultCPUModel
		_c.mutation.SetCPUModel(v)
	}
	if _, ok := _c.mutation.CPUCores(); !ok {
		v := inventory.DefaultCPUCores
		_c.mutation.SetCPUCores(v)
	}
	if _, ok := _c.mutation.CPUFreqMhz(); !ok {
		v := inventory.DefaultCPUFreqMhz
		_c.mutation.SetCPUFreqMhz(v)
	}
	if _, ok := _c.mutation.RAMMib(); !ok {
		v := inventory.DefaultRAMMib
		_c.mutation.SetRAMMib(v)
	}
	if _, ok := _c.mutation.HdModel(); !ok {
		v := inventory.DefaultHdModel
		_c.mutation.SetHdModel(v)
	}
	if _, ok := _c.mutation.HdSizeGB(); !ok {
		v := inventory.DefaultHdSizeGB
		_c.mutation.SetHdSizeGB(v)
	}
	if _, ok := _c.mutation.Manufacturer(); !ok {
		v := inventory.DefaultManufacturer
		_c.mutation.SetManufacturer(v)
	}
	if _, ok := _c.mutation.Product(); !ok {
		v := inventory.DefaultProduct
		_c.mutation.SetProduct(v)
	}
	if _, ok := _c.mutation.Serial(); !ok {
		v := inventory.DefaultSerial
		_c.mutation.SetSerial(v)
	}
	if _, ok := _c.mutation.UUID(); !ok {
		v := inventory.DefaultUUID
		_c.mutation.SetUUID(v)
	}
	if _, ok := _c.mutation.BiosVersion(); !ok {
		v := inventory.DefaultBiosVersion
		_c.mutation.SetBiosVersion(v)
	}
	if _, ok := _c.mutation.PrimaryMAC(); !ok {
		v := inventory.DefaultPrimaryMAC
		_c.mutation.SetPrimaryMAC(v)
	}
	if _, ok := _c.mutation.OsName(); !ok {
		v := inventory.DefaultOsName
		_c.mutation.SetOsName(v)
	}
	if _, ok := _c.mutation.OsVersion(); !ok {
		v := inventory.DefaultOsVersion
		_c.mutation.SetOsVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inventory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := inventory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := inventory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryCreate) check() error {
	if _, ok := _c.mutation.HostID(); !ok {
		return &ValidationError{Name: "host_id", err: errors.New(`ent: missing required field "Inventory.host_id"`)}
	}
	if _, ok := _c.mutation.CPUModel(); !ok {
		return &ValidationError{Name: "cpu_model", err: errors.New(`ent: missing required field "Inventory.cpu_model"`)}
	}
	if _, ok := _c.mutation.CPUCores(); !ok {
		return &ValidationError{Name: "cpu_cores", err: errors.New(`ent: missing required field "Inventory.cpu_cores"`)}
	}
	if _, ok := _c.mutation.CPUFreqMhz(); !ok {
		return &ValidationError{Name: "cpu_freq_mhz", err: errors.New(`ent: missing required field "Inventory.cpu_freq_mhz"`)}
	}
	if _, ok := _c.mutation.RAMMib(); !ok {
		return &ValidationError{Name: "ram_mib", err: errors.New(`ent: missing required field "Inventory.ram_mib"`)}
	}
	if _, ok := _c.mutation.HdModel(); !ok {
		return &ValidationError{Name: "hd_model", err: errors.New(`ent: missing required field "Inventory.hd_model"`)}
	}
	if _, ok := _c.mutation.HdSizeGB(); !ok {
		return &ValidationError{Name: "hd_size_gb", err: errors.New(`ent: missing required field "Inventory.hd_size_gb"`)}
	}
	if _, ok := _c.mutation.Manufacturer(); !ok {
		return &ValidationError{Name: "manufacturer", err: errors.New(`ent: missing required field "Inventory.manufacturer"`)}
	}
	if _, ok := _c.mutation.Product(); !ok {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required field "Inventory.product"`)}
	}
	if _, ok := _c.mutation.Serial(); !ok {
		return &ValidationError{Name: "serial", err: errors.New(`ent: missing required field "Inventory.serial"`)}
	}
	if _, ok := _c.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "Inventory.uuid"`)}
	}
	if _, ok := _c.mutation.BiosVersion(); !ok {
		return &ValidationError{Name: "bios_version", err: errors.New(`ent: missing required field "Inventory.bios_version"`)}
	}
	if _, ok := _c.mutation.PrimaryMAC(); !ok {
		return &ValidationError{Name: "primary_mac", err: errors.New(`ent: missing required field "Inventory.primary_mac"`)}
	}
	if _, ok := _c.mutation.OsName(); !ok {
		return &ValidationError{Name: "os_name", err: errors.New(`ent: missing required field "Inventory.os_name"`)}
	}
	if _, ok := _c.mutation.OsVersion(); !ok {
		return &ValidationError{Name: "os_version", err: errors.New(`ent: missing required field "Inventory.os_version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Inventory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Inventory.updated_at"`)}
	}
	if len(_c.mutation.HostIDs()) == 0 {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required edge "Inventory.host"`)}
	}
	return nil
}

func (_c *InventoryCreate) sqlSave(ctx context.Context) (*Inventory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryCreate) createSpec() (*Inventory, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventory.Table, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CPUModel(); ok {
		_spec.SetField(inventory.FieldCPUModel, field.TypeString, value)
		_node.CPUModel = value
	}
	if value, ok := _c.mutation.CPUCores(); ok {
		_spec.SetField(inventory.FieldCPUCores, field.TypeInt, value)
		_node.CPUCores = value
	}
	if value, ok := _c.mutation.CPUFreqMhz(); ok {
		_spec.SetField(inventory.FieldCPUFreqMhz, field.TypeInt, value)
		_node.CPUFreqMhz = value
	}
	if value, ok := _c.mutation.RAMMib(); ok {
		_spec.SetField(inventory.FieldRAMMib, field.TypeInt, value)
		_node.RAMMib = value
	}
	if value, ok := _c.mutation.HdModel(); ok {
		_spec.SetField(inventory.FieldHdModel, field.TypeString, value)
		_node.HdModel = value
	}
	if value, ok := _c.mutation.HdSizeGB(); ok {
		_spec.SetField(inventory.FieldHdSizeGB, field.TypeInt, value)
		_node.HdSizeGB = value
	}
	if value, ok := _c.mutation.Manufacturer(); ok {
		_spec.SetField(inventory.FieldManufacturer, field.TypeString, value)
		_node.Manufacturer = value
	}
	if value, ok := _c.mutation.Product(); ok {
		_spec.SetField(inventory.FieldProduct, field.TypeString, value)
		_node.Product = value
	}
	if value, ok := _c.mutation.Serial(); ok {
		_spec.SetField(inventory.FieldSerial, field.TypeString, value)
		_node.Serial = value
	}
	if value, ok := _c.mutation.UUID(); ok {
		_spec.SetField(inventory.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := _c.mutation.BiosVersion(); ok {
		_spec.SetField(inventory.FieldBiosVersion, field.TypeString, value)
		_node.BiosVersion = value
	}
	if value, ok := _c.mutation.PrimaryMAC(); ok {
		_spec.SetField(inventory.FieldPrimaryMAC, field.TypeString, value)
		_node.PrimaryMAC = value
	}
	if value, ok := _c.mutation.OsName(); ok {
		_spec.SetField(inventory.FieldOsName, field.TypeString, value)
		_node.OsName = value
	}
	if value, ok := _c.mutation.OsVersion(); ok {
		_spec.SetField(inventory.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inventory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(inventory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   inventory.HostTable,
			Columns: []string{inventory.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inventory.Create().
//		SetHostID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryUpsert) {
//			SetHostID(v+v).
//		}).
//		Exec(ctx)
func (_c *InventoryCreate) OnConflict(opts ...sql.ConflictOption) *InventoryUpsertOne {
	_c.conflict = opts
	return &InventoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventoryCreate) OnConflictColumns(columns ...string) *InventoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventoryUpsertOne{
		create: _c,
	}
}

type (
	// InventoryUpsertOne is the builder for "upsert"-ing
	//  one Inventory node.
	InventoryUpsertOne struct {
		create *InventoryCreate
	}

	// InventoryUpsert is the "OnConflict" setter.
	InventoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetHostID sets the "host_id" field.
func (u *InventoryUpsert) SetHostID(v uuid.UUID) *InventoryUpsert {
	u.Set(inventory.FieldHostID, v)
	return u
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateHostID() *InventoryUpsert {
	u.SetExcluded(inventory.FieldHostID)
	return u
}

// SetCPUModel sets the "cpu_model" field.
func (u *InventoryUpsert) SetCPUModel(v string) *InventoryUpsert {
	u.Set(inventory.FieldCPUModel, v)
	return u
}

// UpdateCPUModel sets the "cpu_model" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateCPUModel() *InventoryUpsert {
	u.SetExcluded(inventory.FieldCPUModel)
	return u
}

// SetCPUCores sets the "cpu_cores" field.
func (u *InventoryUpsert) SetCPUCores(v int) *InventoryUpsert {
	u.Set(inventory.FieldCPUCores, v)
	return u
}

// UpdateCPUCores sets the "cpu_cores" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateCPUCores() *InventoryUpsert {
	u.SetExcluded(inventory.FieldCPUCores)
	return u
}

// AddCPUCores adds v to the "cpu_cores" field.
func (u *InventoryUpsert) AddCPUCores(v int) *InventoryUpsert {
	u.Add(inventory.FieldCPUCores, v)
	return u
}

// SetCPUFreqMhz sets the "cpu_freq_mhz" field.
func (u *InventoryUpsert) SetCPUFreqMhz(v int) *InventoryUpsert {
	u.Set(inventory.FieldCPUFreqMhz, v)
	return u
}

// UpdateCPUFreqMhz sets the "cpu_freq_mhz" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateCPUFreqMhz() *InventoryUpsert {
	u.SetExcluded(inventory.FieldCPUFreqMhz)
	return u
}

// AddCPUFreqMhz adds v to the "cpu_freq_mhz" field.
func (u *InventoryUpsert) AddCPUFreqMhz(v int) *InventoryUpsert {
	u.Add(inventory.FieldCPUFreqMhz, v)
	return u
}

// SetRAMMib sets the "ram_mib" field.
func (u *InventoryUpsert) SetRAMMib(v int) *InventoryUpsert {
	u.Set(inventory.FieldRAMMib, v)
	return u
}

// UpdateRAMMib sets the "ram_mib" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateRAMMib() *InventoryUpsert {
	u.SetExcluded(inventory.FieldRAMMib)
	return u
}

// AddRAMMib adds v to the "ram_mib" field.
func (u *InventoryUpsert) AddRAMMib(v int) *InventoryUpsert {
	u.Add(inventory.FieldRAMMib, v)
	return u
}

// SetHdModel sets the "hd_model" field.
func (u *InventoryUpsert) SetHdModel(v string) *InventoryUpsert {
	u.Set(inventory.FieldHdModel, v)
	return u
}

// UpdateHdModel sets the "hd_model" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateHdModel() *InventoryUpsert {
	u.SetExcluded(inventory.FieldHdModel)
	return u
}

// SetHdSizeGB sets the "hd_size_gb" field.
func (u *InventoryUpsert) SetHdSizeGB(v int) *InventoryUpsert {
	u.Set(inventory.FieldHdSizeGB, v)
	return u
}

// UpdateHdSizeGB sets the "hd_size_gb" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateHdSizeGB() *InventoryUpsert {
	u.SetExcluded(inventory.FieldHdSizeGB)
	return u
}

// AddHdSizeGB adds v to the "hd_size_gb" field.
func (u *InventoryUpsert) AddHdSizeGB(v int) *InventoryUpsert {
	u.Add(inventory.FieldHdSizeGB, v)
	return u
}

// SetManufacturer sets the "manufacturer" field.
func (u *InventoryUpsert) SetManufacturer(v string) *InventoryUpsert {
	u.Set(inventory.FieldManufacturer, v)
	return u
}

// UpdateManufacturer sets the "manufacturer" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateManufacturer() *InventoryUpsert {
	u.SetExcluded(inventory.FieldManufacturer)
	return u
}

// SetProduct sets the "product" field.
func (u *InventoryUpsert) SetProduct(v string) *InventoryUpsert {
	u.Set(inventory.FieldProduct, v)
	return u
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateProduct() *InventoryUpsert {
	u.SetExcluded(inventory.FieldProduct)
	return u
}

// SetSerial sets the "serial" field.
func (u *InventoryUpsert) SetSerial(v string) *InventoryUpsert {
	u.Set(inventory.FieldSerial, v)
	return u
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateSerial() *InventoryUpsert {
	u.SetExcluded(inventory.FieldSerial)
	return u
}

// SetUUID sets the "uuid" field.
func (u *InventoryUpsert) SetUUID(v string) *InventoryUpsert {
	u.Set(inventory.FieldUUID, v)
	return u
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateUUID() *InventoryUpsert {
	u.SetExcluded(inventory.FieldUUID)
	return u
}

// SetBiosVersion sets the "bios_version" field.
func (u *InventoryUpsert) SetBiosVersion(v string) *InventoryUpsert {
	u.Set(inventory.FieldBiosVersion, v)
	return u
}

// UpdateBiosVersion sets the "bios_version" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateBiosVersion() *InventoryUpsert {
	u.SetExcluded(inventory.FieldBiosVersion)
	return u
}

// SetPrimaryMAC sets the "primary_mac" field.
func (u *InventoryUpsert) SetPrimaryMAC(v string) *InventoryUpsert {
	u.Set(inventory.FieldPrimaryMAC, v)
	return u
}

// UpdatePrimaryMAC sets the "primary_mac" field to the value that was provided on create.
func (u *InventoryUpsert) UpdatePrimaryMAC() *InventoryUpsert {
	u.SetExcluded(inventory.FieldPrimaryMAC)
	return u
}

// SetOsName sets the "os_name" field.
func (u *InventoryUpsert) SetOsName(v string) *InventoryUpsert {
	u.Set(inventory.FieldOsName, v)
	return u
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateOsName() *InventoryUpsert {
	u.SetExcluded(inventory.FieldOsName)
	return u
}

// SetOsVersion sets the "os_version" field.
func (u *InventoryUpsert) SetOsVersion(v string) *InventoryUpsert {
	u.Set(inventory.FieldOsVersion, v)
	return u
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateOsVersion() *InventoryUpsert {
	u.SetExcluded(inventory.FieldOsVersion)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InventoryUpsert) SetUpdatedAt(v time.Time) *InventoryUpsert {
	u.Set(inventory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InventoryUpsert) UpdateUpdatedAt() *InventoryUpsert {
	u.SetExcluded(inventory.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryUpsertOne) UpdateNewValues() *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(inventory.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(inventory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inventory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventoryUpsertOne) Ignore() *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryUpsertOne) DoNothing() *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryCreate.OnConflict
// documentation for more info.
func (u *InventoryUpsertOne) Update(set func(*InventoryUpsert)) *InventoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostID sets the "host_id" field.
func (u *InventoryUpsertOne) SetHostID(v uuid.UUID) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateHostID() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateHostID()
	})
}

// SetCPUModel sets the "cpu_model" field.
func (u *InventoryUpsertOne) SetCPUModel(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCPUModel(v)
	})
}

// UpdateCPUModel sets the "cpu_model" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateCPUModel() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCPUModel()
	})
}

// SetCPUCores sets the "cpu_cores" field.
func (u *InventoryUpsertOne) SetCPUCores(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCPUCores(v)
	})
}

// AddCPUCores adds v to the "cpu_cores" field.
func (u *InventoryUpsertOne) AddCPUCores(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.AddCPUCores(v)
	})
}

// UpdateCPUCores sets the "cpu_cores" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateCPUCores() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCPUCores()
	})
}

// SetCPUFreqMhz sets the "cpu_freq_mhz" field.
func (u *InventoryUpsertOne) SetCPUFreqMhz(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCPUFreqMhz(v)
	})
}

// AddCPUFreqMhz adds v to the "cpu_freq_mhz" field.
func (u *InventoryUpsertOne) AddCPUFreqMhz(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.AddCPUFreqMhz(v)
	})
}

// UpdateCPUFreqMhz sets the "cpu_freq_mhz" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateCPUFreqMhz() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCPUFreqMhz()
	})
}

// SetRAMMib sets the "ram_mib" field.
func (u *InventoryUpsertOne) SetRAMMib(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetRAMMib(v)
	})
}

// AddRAMMib adds v to the "ram_mib" field.
func (u *InventoryUpsertOne) AddRAMMib(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.AddRAMMib(v)
	})
}

// UpdateRAMMib sets the "ram_mib" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateRAMMib() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateRAMMib()
	})
}

// SetHdModel sets the "hd_model" field.
func (u *InventoryUpsertOne) SetHdModel(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetHdModel(v)
	})
}

// UpdateHdModel sets the "hd_model" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateHdModel() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateHdModel()
	})
}

// SetHdSizeGB sets the "hd_size_gb" field.
func (u *InventoryUpsertOne) SetHdSizeGB(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetHdSizeGB(v)
	})
}

// AddHdSizeGB adds v to the "hd_size_gb" field.
func (u *InventoryUpsertOne) AddHdSizeGB(v int) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.AddHdSizeGB(v)
	})
}

// UpdateHdSizeGB sets the "hd_size_gb" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateHdSizeGB() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateHdSizeGB()
	})
}

// SetManufacturer sets the "manufacturer" field.
func (u *InventoryUpsertOne) SetManufacturer(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetManufacturer(v)
	})
}

// UpdateManufacturer sets the "manufacturer" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateManufacturer() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateManufacturer()
	})
}

// SetProduct sets the "product" field.
func (u *InventoryUpsertOne) SetProduct(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateProduct() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateProduct()
	})
}

// SetSerial sets the "serial" field.
func (u *InventoryUpsertOne) SetSerial(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateSerial() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateSerial()
	})
}

// SetUUID sets the "uuid" field.
func (u *InventoryUpsertOne) SetUUID(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateUUID() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateUUID()
	})
}

// SetBiosVersion sets the "bios_version" field.
func (u *InventoryUpsertOne) SetBiosVersion(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetBiosVersion(v)
	})
}

// UpdateBiosVersion sets the "bios_version" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateBiosVersion() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateBiosVersion()
	})
}

// SetPrimaryMAC sets the "primary_mac" field.
func (u *InventoryUpsertOne) SetPrimaryMAC(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetPrimaryMAC(v)
	})
}

// UpdatePrimaryMAC sets the "primary_mac" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdatePrimaryMAC() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdatePrimaryMAC()
	})
}

// SetOsName sets the "os_name" field.
func (u *InventoryUpsertOne) SetOsName(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetOsName(v)
	})
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateOsName() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateOsName()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *InventoryUpsertOne) SetOsVersion(v string) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateOsVersion() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateOsVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InventoryUpsertOne) SetUpdatedAt(v time.Time) *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InventoryUpsertOne) UpdateUpdatedAt() *InventoryUpsertOne {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InventoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventoryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InventoryUpsertOne.ID is not supported by MySQL driver. Use InventoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventoryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventoryCreateBulk is the builder for creating many Inventory entities in bulk.
type InventoryCreateBulk struct {
	config
	err      error
	builders []*InventoryCreate
	conflict []sql.ConflictOption
}

// Save creates the Inventory entities in the database.
func (_c *InventoryCreateBulk) Save(ctx context.Context) ([]*Inventory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Inventory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryCreateBulk) SaveX(ctx context.Context) []*Inventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inventory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryUpsert) {
//			SetHostID(v+v).
//		}).
//		Exec(ctx)
func (_c *InventoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventoryUpsertBulk {
	_c.conflict = opts
	return &InventoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventoryCreateBulk) OnConflictColumns(columns ...string) *InventoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventoryUpsertBulk{
		create: _c,
	}
}

// InventoryUpsertBulk is the builder for "upsert"-ing
// a bulk of Inventory nodes.
type InventoryUpsertBulk struct {
	create *InventoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryUpsertBulk) UpdateNewValues() *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(inventory.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(inventory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inventory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventoryUpsertBulk) Ignore() *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryUpsertBulk) DoNothing() *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryCreateBulk.OnConflict
// documentation for more info.
func (u *InventoryUpsertBulk) Update(set func(*InventoryUpsert)) *InventoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostID sets the "host_id" field.
func (u *InventoryUpsertBulk) SetHostID(v uuid.UUID) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateHostID() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateHostID()
	})
}

// SetCPUModel sets the "cpu_model" field.
func (u *InventoryUpsertBulk) SetCPUModel(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCPUModel(v)
	})
}

// UpdateCPUModel sets the "cpu_model" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateCPUModel() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCPUModel()
	})
}

// SetCPUCores sets the "cpu_cores" field.
func (u *InventoryUpsertBulk) SetCPUCores(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCPUCores(v)
	})
}

// AddCPUCores adds v to the "cpu_cores" field.
func (u *InventoryUpsertBulk) AddCPUCores(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.AddCPUCores(v)
	})
}

// UpdateCPUCores sets the "cpu_cores" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateCPUCores() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCPUCores()
	})
}

// SetCPUFreqMhz sets the "cpu_freq_mhz" field.
func (u *InventoryUpsertBulk) SetCPUFreqMhz(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetCPUFreqMhz(v)
	})
}

// AddCPUFreqMhz adds v to the "cpu_freq_mhz" field.
func (u *InventoryUpsertBulk) AddCPUFreqMhz(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.AddCPUFreqMhz(v)
	})
}

// UpdateCPUFreqMhz sets the "cpu_freq_mhz" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateCPUFreqMhz() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateCPUFreqMhz()
	})
}

// SetRAMMib sets the "ram_mib" field.
func (u *InventoryUpsertBulk) SetRAMMib(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetRAMMib(v)
	})
}

// AddRAMMib adds v to the "ram_mib" field.
func (u *InventoryUpsertBulk) AddRAMMib(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.AddRAMMib(v)
	})
}

// UpdateRAMMib sets the "ram_mib" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateRAMMib() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateRAMMib()
	})
}

// SetHdModel sets the "hd_model" field.
func (u *InventoryUpsertBulk) SetHdModel(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetHdModel(v)
	})
}

// UpdateHdModel sets the "hd_model" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateHdModel() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateHdModel()
	})
}

// SetHdSizeGB sets the "hd_size_gb" field.
func (u *InventoryUpsertBulk) SetHdSizeGB(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetHdSizeGB(v)
	})
}

// AddHdSizeGB adds v to the "hd_size_gb" field.
func (u *InventoryUpsertBulk) AddHdSizeGB(v int) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.AddHdSizeGB(v)
	})
}

// UpdateHdSizeGB sets the "hd_size_gb" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateHdSizeGB() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateHdSizeGB()
	})
}

// SetManufacturer sets the "manufacturer" field.
func (u *InventoryUpsertBulk) SetManufacturer(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetManufacturer(v)
	})
}

// UpdateManufacturer sets the "manufacturer" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateManufacturer() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateManufacturer()
	})
}

// SetProduct sets the "product" field.
func (u *InventoryUpsertBulk) SetProduct(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateProduct() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateProduct()
	})
}

// SetSerial sets the "serial" field.
func (u *InventoryUpsertBulk) SetSerial(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateSerial() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateSerial()
	})
}

// SetUUID sets the "uuid" field.
func (u *InventoryUpsertBulk) SetUUID(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateUUID() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateUUID()
	})
}

// SetBiosVersion sets the "bios_version" field.
func (u *InventoryUpsertBulk) SetBiosVersion(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetBiosVersion(v)
	})
}

// UpdateBiosVersion sets the "bios_version" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateBiosVersion() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateBiosVersion()
	})
}

// SetPrimaryMAC sets the "primary_mac" field.
func (u *InventoryUpsertBulk) SetPrimaryMAC(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetPrimaryMAC(v)
	})
}

// UpdatePrimaryMAC sets the "primary_mac" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdatePrimaryMAC() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdatePrimaryMAC()
	})
}

// SetOsName sets the "os_name" field.
func (u *InventoryUpsertBulk) SetOsName(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetOsName(v)
	})
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateOsName() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateOsName()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *InventoryUpsertBulk) SetOsVersion(v string) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateOsVersion() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateOsVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InventoryUpsertBulk) SetUpdatedAt(v time.Time) *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InventoryUpsertBulk) UpdateUpdatedAt() *InventoryUpsertBulk {
	return u.Update(func(s *InventoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InventoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
