// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/module"
	"github.com/nemvince/fog-next/ent/modulestatus"
)

// ModuleStatusCreate is the builder for creating a ModuleStatus entity.
type ModuleStatusCreate struct {
	config
	mutation *ModuleStatusMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHostID sets the "host_id" field.
func (_c *ModuleStatusCreate) SetHostID(v uuid.UUID) *ModuleStatusCreate {
	_c.mutation.SetHostID(v)
	return _c
}

// SetModuleID sets the "module_id" field.
func (_c *ModuleStatusCreate) SetModuleID(v uuid.UUID) *ModuleStatusCreate {
	_c.mutation.SetModuleID(v)
	return _c
}

// SetIsOn sets the "is_on" field.
func (_c *ModuleStatusCreate) SetIsOn(v bool) *ModuleStatusCreate {
	_c.mutation.SetIsOn(v)
	return _c
}

// SetNillableIsOn sets the "is_on" field if the given value is not nil.
func (_c *ModuleStatusCreate) SetNillableIsOn(v *bool) *ModuleStatusCreate {
	if v != nil {
		_c.SetIsOn(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModuleStatusCreate) SetID(v uuid.UUID) *ModuleStatusCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ModuleStatusCreate) SetNillableID(v *uuid.UUID) *ModuleStatusCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetModule sets the "module" edge to the Module entity.
func (_c *ModuleStatusCreate) SetModule(v *Module) *ModuleStatusCreate {
	return _c.SetModuleID(v.ID)
}

// Mutation returns the ModuleStatusMutation object of the builder.
func (_c *ModuleStatusCreate) Mutation() *ModuleStatusMutation {
	return _c.mutation
}

// Save creates the ModuleStatus in the database.
func (_c *ModuleStatusCreate) Save(ctx context.Context) (*ModuleStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModuleStatusCreate) SaveX(ctx context.Context) *ModuleStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModuleStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModuleStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModuleStatusCreate) defaults() {
	if _, ok := _c.mutation.IsOn(); !ok {
		v := modulestatus.DefaultIsOn
		_c.mutation.SetIsOn(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := modulestatus.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModuleStatusCreate) check() error {
	if _, ok := _c.mutation.HostID(); !ok {
		return &ValidationError{Name: "host_id", err: errors.New(`ent: missing required field "ModuleStatus.host_id"`)}
	}
	if _, ok := _c.mutation.ModuleID(); !ok {
		return &ValidationError{Name: "module_id", err: errors.New(`ent: missing required field "ModuleStatus.module_id"`)}
	}
	if _, ok := _c.mutation.IsOn(); !ok {
		return &ValidationError{Name: "is_on", err: errors.New(`ent: missing required field "ModuleStatus.is_on"`)}
	}
	if len(_c.mutation.ModuleIDs()) == 0 {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required edge "ModuleStatus.module"`)}
	}
	return nil
}

func (_c *ModuleStatusCreate) sqlSave(ctx context.Context) (*ModuleStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModuleStatusCreate) createSpec() (*ModuleStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &ModuleStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modulestatus.Table, sqlgraph.NewFieldSpec(modulestatus.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.HostID(); ok {
		_spec.SetField(modulestatus.FieldHostID, field.TypeUUID, value)
		_node.HostID = value
	}
	if value, ok := _c.mutation.IsOn(); ok {
		_spec.SetField(modulestatus.FieldIsOn, field.TypeBool, value)
		_node.IsOn = value
	}
	if nodes := _c.mutation.ModuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modulestatus.ModuleTable,
			Columns: []string{modulestatus.ModuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(module.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModuleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModuleStatus.Create().
//		SetHostID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModuleStatusUpsert) {
//			SetHostID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModuleStatusCreate) OnConflict(opts ...sql.ConflictOption) *ModuleStatusUpsertOne {
	_c.conflict = opts
	return &ModuleStatusUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModuleStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModuleStatusCreate) OnConflictColumns(columns ...string) *ModuleStatusUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModuleStatusUpsertOne{
		create: _c,
	}
}

type (
	// ModuleStatusUpsertOne is the builder for "upsert"-ing
	//  one ModuleStatus node.
	ModuleStatusUpsertOne struct {
		create *ModuleStatusCreate
	}

	// ModuleStatusUpsert is the "OnConflict" setter.
	ModuleStatusUpsert struct {
		*sql.UpdateSet
	}
)

// SetHostID sets the "host_id" field.
func (u *ModuleStatusUpsert) SetHostID(v uuid.UUID) *ModuleStatusUpsert {
	u.Set(modulestatus.FieldHostID, v)
	return u
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *ModuleStatusUpsert) UpdateHostID() *ModuleStatusUpsert {
	u.SetExcluded(modulestatus.FieldHostID)
	return u
}

// SetModuleID sets the "module_id" field.
func (u *ModuleStatusUpsert) SetModuleID(v uuid.UUID) *ModuleStatusUpsert {
	u.Set(modulestatus.FieldModuleID, v)
	return u
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *ModuleStatusUpsert) UpdateModuleID() *ModuleStatusUpsert {
	u.SetExcluded(modulestatus.FieldModuleID)
	return u
}

// SetIsOn sets the "is_on" field.
func (u *ModuleStatusUpsert) SetIsOn(v bool) *ModuleStatusUpsert {
	u.Set(modulestatus.FieldIsOn, v)
	return u
}

// UpdateIsOn sets the "is_on" field to the value that was provided on create.
func (u *ModuleStatusUpsert) UpdateIsOn() *ModuleStatusUpsert {
	u.SetExcluded(modulestatus.FieldIsOn)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ModuleStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(modulestatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ModuleStatusUpsertOne) UpdateNewValues() *ModuleStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(modulestatus.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModuleStatus.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModuleStatusUpsertOne) Ignore() *ModuleStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModuleStatusUpsertOne) DoNothing() *ModuleStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModuleStatusCreate.OnConflict
// documentation for more info.
func (u *ModuleStatusUpsertOne) Update(set func(*ModuleStatusUpsert)) *ModuleStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModuleStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostID sets the "host_id" field.
func (u *ModuleStatusUpsertOne) SetHostID(v uuid.UUID) *ModuleStatusUpsertOne {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *ModuleStatusUpsertOne) UpdateHostID() *ModuleStatusUpsertOne {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.UpdateHostID()
	})
}

// SetModuleID sets the "module_id" field.
func (u *ModuleStatusUpsertOne) SetModuleID(v uuid.UUID) *ModuleStatusUpsertOne {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.SetModuleID(v)
	})
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *ModuleStatusUpsertOne) UpdateModuleID() *ModuleStatusUpsertOne {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.UpdateModuleID()
	})
}

// SetIsOn sets the "is_on" field.
func (u *ModuleStatusUpsertOne) SetIsOn(v bool) *ModuleStatusUpsertOne {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.SetIsOn(v)
	})
}

// UpdateIsOn sets the "is_on" field to the value that was provided on create.
func (u *ModuleStatusUpsertOne) UpdateIsOn() *ModuleStatusUpsertOne {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.UpdateIsOn()
	})
}

// Exec executes the query.
func (u *ModuleStatusUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModuleStatusCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModuleStatusUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModuleStatusUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ModuleStatusUpsertOne.ID is not supported by MySQL driver. Use ModuleStatusUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModuleStatusUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModuleStatusCreateBulk is the builder for creating many ModuleStatus entities in bulk.
type ModuleStatusCreateBulk struct {
	config
	err      error
	builders []*ModuleStatusCreate
	conflict []sql.ConflictOption
}

// Save creates the ModuleStatus entities in the database.
func (_c *ModuleStatusCreateBulk) Save(ctx context.Context) ([]*ModuleStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModuleStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModuleStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModuleStatusCreateBulk) SaveX(ctx context.Context) []*ModuleStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModuleStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModuleStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModuleStatus.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModuleStatusUpsert) {
//			SetHostID(v+v).
//		}).
//		Exec(ctx)
func (_c *ModuleStatusCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModuleStatusUpsertBulk {
	_c.conflict = opts
	return &ModuleStatusUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModuleStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModuleStatusCreateBulk) OnConflictColumns(columns ...string) *ModuleStatusUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModuleStatusUpsertBulk{
		create: _c,
	}
}

// ModuleStatusUpsertBulk is the builder for "upsert"-ing
// a bulk of ModuleStatus nodes.
type ModuleStatusUpsertBulk struct {
	create *ModuleStatusCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModuleStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(modulestatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ModuleStatusUpsertBulk) UpdateNewValues() *ModuleStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(modulestatus.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModuleStatus.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModuleStatusUpsertBulk) Ignore() *ModuleStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModuleStatusUpsertBulk) DoNothing() *ModuleStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModuleStatusCreateBulk.OnConflict
// documentation for more info.
func (u *ModuleStatusUpsertBulk) Update(set func(*ModuleStatusUpsert)) *ModuleStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModuleStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostID sets the "host_id" field.
func (u *ModuleStatusUpsertBulk) SetHostID(v uuid.UUID) *ModuleStatusUpsertBulk {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *ModuleStatusUpsertBulk) UpdateHostID() *ModuleStatusUpsertBulk {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.UpdateHostID()
	})
}

// SetModuleID sets the "module_id" field.
func (u *ModuleStatusUpsertBulk) SetModuleID(v uuid.UUID) *ModuleStatusUpsertBulk {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.SetModuleID(v)
	})
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *ModuleStatusUpsertBulk) UpdateModuleID() *ModuleStatusUpsertBulk {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.UpdateModuleID()
	})
}

// SetIsOn sets the "is_on" field.
func (u *ModuleStatusUpsertBulk) SetIsOn(v bool) *ModuleStatusUpsertBulk {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.SetIsOn(v)
	})
}

// UpdateIsOn sets the "is_on" field to the value that was provided on create.
func (u *ModuleStatusUpsertBulk) UpdateIsOn() *ModuleStatusUpsertBulk {
	return u.Update(func(s *ModuleStatusUpsert) {
		s.UpdateIsOn()
	})
}

// Exec executes the query.
func (u *ModuleStatusUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModuleStatusCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModuleStatusCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModuleStatusUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
