// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/module"
	"github.com/nemvince/fog-next/ent/modulestatus"
)

// ModuleStatus is the model entity for the ModuleStatus schema.
type ModuleStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// HostID holds the value of the "host_id" field.
	HostID uuid.UUID `json:"hostId"`
	// ModuleID holds the value of the "module_id" field.
	ModuleID uuid.UUID `json:"moduleId"`
	// IsOn holds the value of the "is_on" field.
	IsOn bool `json:"isOn"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModuleStatusQuery when eager-loading is set.
	Edges        ModuleStatusEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModuleStatusEdges holds the relations/edges for other nodes in the graph.
type ModuleStatusEdges struct {
	// Module holds the value of the module edge.
	Module *Module `json:"module,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModuleOrErr returns the Module value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModuleStatusEdges) ModuleOrErr() (*Module, error) {
	if e.Module != nil {
		return e.Module, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: module.Label}
	}
	return nil, &NotLoadedError{edge: "module"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModuleStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modulestatus.FieldIsOn:
			values[i] = new(sql.NullBool)
		case modulestatus.FieldID, modulestatus.FieldHostID, modulestatus.FieldModuleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModuleStatus fields.
func (_m *ModuleStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modulestatus.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case modulestatus.FieldHostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field host_id", values[i])
			} else if value != nil {
				_m.HostID = *value
			}
		case modulestatus.FieldModuleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value != nil {
				_m.ModuleID = *value
			}
		case modulestatus.FieldIsOn:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_on", values[i])
			} else if value.Valid {
				_m.IsOn = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModuleStatus.
// This includes values selected through modifiers, order, etc.
func (_m *ModuleStatus) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModule queries the "module" edge of the ModuleStatus entity.
func (_m *ModuleStatus) QueryModule() *ModuleQuery {
	return NewModuleStatusClient(_m.config).QueryModule(_m)
}

// Update returns a builder for updating this ModuleStatus.
// Note that you need to call ModuleStatus.Unwrap() before calling this method if this ModuleStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModuleStatus) Update() *ModuleStatusUpdateOne {
	return NewModuleStatusClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModuleStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModuleStatus) Unwrap() *ModuleStatus {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModuleStatus is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModuleStatus) String() string {
	var builder strings.Builder
	builder.WriteString("ModuleStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("host_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HostID))
	builder.WriteString(", ")
	builder.WriteString("module_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModuleID))
	builder.WriteString(", ")
	builder.WriteString("is_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOn))
	builder.WriteByte(')')
	return builder.String()
}

// ModuleStatusSlice is a parsable slice of ModuleStatus.
type ModuleStatusSlice []*ModuleStatus
