// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/ostype"
)

// OSType is the model entity for the OSType schema.
type OSType struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OSTypeQuery when eager-loading is set.
	Edges        OSTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OSTypeEdges holds the relations/edges for other nodes in the graph.
type OSTypeEdges struct {
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	namedImages map[string][]*Image
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e OSTypeEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[0] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OSType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ostype.FieldName:
			values[i] = new(sql.NullString)
		case ostype.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OSType fields.
func (_m *OSType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ostype.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ostype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OSType.
// This includes values selected through modifiers, order, etc.
func (_m *OSType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryImages queries the "images" edge of the OSType entity.
func (_m *OSType) QueryImages() *ImageQuery {
	return NewOSTypeClient(_m.config).QueryImages(_m)
}

// Update returns a builder for updating this OSType.
// Note that you need to call OSType.Unwrap() before calling this method if this OSType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OSType) Update() *OSTypeUpdateOne {
	return NewOSTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OSType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OSType) Unwrap() *OSType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OSType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OSType) String() string {
	var builder strings.Builder
	builder.WriteString("OSType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NamedImages returns the Images named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *OSType) NamedImages(name string) ([]*Image, error) {
	if _m.Edges.namedImages == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedImages[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *OSType) appendNamedImages(name string, edges ...*Image) {
	if _m.Edges.namedImages == nil {
		_m.Edges.namedImages = make(map[string][]*Image)
	}
	if len(edges) == 0 {
		_m.Edges.namedImages[name] = []*Image{}
	} else {
		_m.Edges.namedImages[name] = append(_m.Edges.namedImages[name], edges...)
	}
}

// OSTypes is a parsable slice of OSType.
type OSTypes []*OSType
