// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/pendingmac"
)

// PendingMAC is the model entity for the PendingMAC schema.
type PendingMAC struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// MAC holds the value of the "mac" field.
	MAC string `json:"mac"`
	// HostID holds the value of the "host_id" field.
	HostID *uuid.UUID `json:"hostId,omitempty"`
	// SeenAt holds the value of the "seen_at" field.
	SeenAt time.Time `json:"seenAt"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PendingMACQuery when eager-loading is set.
	Edges        PendingMACEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PendingMACEdges holds the relations/edges for other nodes in the graph.
type PendingMACEdges struct {
	// Host holds the value of the host edge.
	Host *Host `json:"host,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HostOrErr returns the Host value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PendingMACEdges) HostOrErr() (*Host, error) {
	if e.Host != nil {
		return e.Host, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: host.Label}
	}
	return nil, &NotLoadedError{edge: "host"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PendingMAC) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pendingmac.FieldHostID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case pendingmac.FieldMAC:
			values[i] = new(sql.NullString)
		case pendingmac.FieldSeenAt:
			values[i] = new(sql.NullTime)
		case pendingmac.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PendingMAC fields.
func (_m *PendingMAC) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pendingmac.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pendingmac.FieldMAC:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mac", values[i])
			} else if value.Valid {
				_m.MAC = value.String
			}
		case pendingmac.FieldHostID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field host_id", values[i])
			} else if value.Valid {
				_m.HostID = new(uuid.UUID)
				*_m.HostID = *value.S.(*uuid.UUID)
			}
		case pendingmac.FieldSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field seen_at", values[i])
			} else if value.Valid {
				_m.SeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PendingMAC.
// This includes values selected through modifiers, order, etc.
func (_m *PendingMAC) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHost queries the "host" edge of the PendingMAC entity.
func (_m *PendingMAC) QueryHost() *HostQuery {
	return NewPendingMACClient(_m.config).QueryHost(_m)
}

// Update returns a builder for updating this PendingMAC.
// Note that you need to call PendingMAC.Unwrap() before calling this method if this PendingMAC
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PendingMAC) Update() *PendingMACUpdateOne {
	return NewPendingMACClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PendingMAC entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PendingMAC) Unwrap() *PendingMAC {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PendingMAC is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PendingMAC) String() string {
	var builder strings.Builder
	builder.WriteString("PendingMAC(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("mac=")
	builder.WriteString(_m.MAC)
	builder.WriteString(", ")
	if v := _m.HostID; v != nil {
		builder.WriteString("host_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("seen_at=")
	builder.WriteString(_m.SeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PendingMACs is a parsable slice of PendingMAC.
type PendingMACs []*PendingMAC
