// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/printer"
	"github.com/nemvince/fog-next/ent/printerassoc"
)

// PrinterAssoc is the model entity for the PrinterAssoc schema.
type PrinterAssoc struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// PrinterID holds the value of the "printer_id" field.
	PrinterID uuid.UUID `json:"printerId"`
	// HostID holds the value of the "host_id" field.
	HostID uuid.UUID `json:"hostId"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"isDefault"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PrinterAssocQuery when eager-loading is set.
	Edges        PrinterAssocEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PrinterAssocEdges holds the relations/edges for other nodes in the graph.
type PrinterAssocEdges struct {
	// Printer holds the value of the printer edge.
	Printer *Printer `json:"printer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PrinterOrErr returns the Printer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PrinterAssocEdges) PrinterOrErr() (*Printer, error) {
	if e.Printer != nil {
		return e.Printer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: printer.Label}
	}
	return nil, &NotLoadedError{edge: "printer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PrinterAssoc) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case printerassoc.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case printerassoc.FieldID, printerassoc.FieldPrinterID, printerassoc.FieldHostID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PrinterAssoc fields.
func (_m *PrinterAssoc) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case printerassoc.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case printerassoc.FieldPrinterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field printer_id", values[i])
			} else if value != nil {
				_m.PrinterID = *value
			}
		case printerassoc.FieldHostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field host_id", values[i])
			} else if value != nil {
				_m.HostID = *value
			}
		case printerassoc.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PrinterAssoc.
// This includes values selected through modifiers, order, etc.
func (_m *PrinterAssoc) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrinter queries the "printer" edge of the PrinterAssoc entity.
func (_m *PrinterAssoc) QueryPrinter() *PrinterQuery {
	return NewPrinterAssocClient(_m.config).QueryPrinter(_m)
}

// Update returns a builder for updating this PrinterAssoc.
// Note that you need to call PrinterAssoc.Unwrap() before calling this method if this PrinterAssoc
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PrinterAssoc) Update() *PrinterAssocUpdateOne {
	return NewPrinterAssocClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PrinterAssoc entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PrinterAssoc) Unwrap() *PrinterAssoc {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PrinterAssoc is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PrinterAssoc) String() string {
	var builder strings.Builder
	builder.WriteString("PrinterAssoc(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("printer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrinterID))
	builder.WriteString(", ")
	builder.WriteString("host_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HostID))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteByte(')')
	return builder.String()
}

// PrinterAssocs is a parsable slice of PrinterAssoc.
type PrinterAssocs []*PrinterAssoc
