// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nemvince/fog-next/ent/predicate"
	"github.com/nemvince/fog-next/ent/printerassoc"
)

// PrinterAssocDelete is the builder for deleting a PrinterAssoc entity.
type PrinterAssocDelete struct {
	config
	hooks    []Hook
	mutation *PrinterAssocMutation
}

// Where appends a list predicates to the PrinterAssocDelete builder.
func (_d *PrinterAssocDelete) Where(ps ...predicate.PrinterAssoc) *PrinterAssocDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PrinterAssocDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PrinterAssocDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PrinterAssocDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(printerassoc.Table, sqlgraph.NewFieldSpec(printerassoc.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PrinterAssocDeleteOne is the builder for deleting a single PrinterAssoc entity.
type PrinterAssocDeleteOne struct {
	_d *PrinterAssocDelete
}

// Where appends a list predicates to the PrinterAssocDelete builder.
func (_d *PrinterAssocDeleteOne) Where(ps ...predicate.PrinterAssoc) *PrinterAssocDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PrinterAssocDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{printerassoc.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PrinterAssocDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
