// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/snapin"
	"github.com/nemvince/fog-next/ent/snapinassoc"
)

// SnapinAssocCreate is the builder for creating a SnapinAssoc entity.
type SnapinAssocCreate struct {
	config
	mutation *SnapinAssocMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSnapinID sets the "snapin_id" field.
func (_c *SnapinAssocCreate) SetSnapinID(v uuid.UUID) *SnapinAssocCreate {
	_c.mutation.SetSnapinID(v)
	return _c
}

// SetHostID sets the "host_id" field.
func (_c *SnapinAssocCreate) SetHostID(v uuid.UUID) *SnapinAssocCreate {
	_c.mutation.SetHostID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SnapinAssocCreate) SetID(v uuid.UUID) *SnapinAssocCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SnapinAssocCreate) SetNillableID(v *uuid.UUID) *SnapinAssocCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSnapin sets the "snapin" edge to the Snapin entity.
func (_c *SnapinAssocCreate) SetSnapin(v *Snapin) *SnapinAssocCreate {
	return _c.SetSnapinID(v.ID)
}

// SetHost sets the "host" edge to the Host entity.
func (_c *SnapinAssocCreate) SetHost(v *Host) *SnapinAssocCreate {
	return _c.SetHostID(v.ID)
}

// Mutation returns the SnapinAssocMutation object of the builder.
func (_c *SnapinAssocCreate) Mutation() *SnapinAssocMutation {
	return _c.mutation
}

// Save creates the SnapinAssoc in the database.
func (_c *SnapinAssocCreate) Save(ctx context.Context) (*SnapinAssoc, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SnapinAssocCreate) SaveX(ctx context.Context) *SnapinAssoc {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapinAssocCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapinAssocCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SnapinAssocCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := snapinassoc.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SnapinAssocCreate) check() error {
	if _, ok := _c.mutation.SnapinID(); !ok {
		return &ValidationError{Name: "snapin_id", err: errors.New(`ent: missing required field "SnapinAssoc.snapin_id"`)}
	}
	if _, ok := _c.mutation.HostID(); !ok {
		return &ValidationError{Name: "host_id", err: errors.New(`ent: missing required field "SnapinAssoc.host_id"`)}
	}
	if len(_c.mutation.SnapinIDs()) == 0 {
		return &ValidationError{Name: "snapin", err: errors.New(`ent: missing required edge "SnapinAssoc.snapin"`)}
	}
	if len(_c.mutation.HostIDs()) == 0 {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required edge "SnapinAssoc.host"`)}
	}
	return nil
}

func (_c *SnapinAssocCreate) sqlSave(ctx context.Context) (*SnapinAssoc, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SnapinAssocCreate) createSpec() (*SnapinAssoc, *sqlgraph.CreateSpec) {
	var (
		_node = &SnapinAssoc{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(snapinassoc.Table, sqlgraph.NewFieldSpec(snapinassoc.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if nodes := _c.mutation.SnapinIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   snapinassoc.SnapinTable,
			Columns: []string{snapinassoc.SnapinColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SnapinID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   snapinassoc.HostTable,
			Columns: []string{snapinassoc.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SnapinAssoc.Create().
//		SetSnapinID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SnapinAssocUpsert) {
//			SetSnapinID(v+v).
//		}).
//		Exec(ctx)
func (_c *SnapinAssocCreate) OnConflict(opts ...sql.ConflictOption) *SnapinAssocUpsertOne {
	_c.conflict = opts
	return &SnapinAssocUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SnapinAssoc.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SnapinAssocCreate) OnConflictColumns(columns ...string) *SnapinAssocUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SnapinAssocUpsertOne{
		create: _c,
	}
}

type (
	// SnapinAssocUpsertOne is the builder for "upsert"-ing
	//  one SnapinAssoc node.
	SnapinAssocUpsertOne struct {
		create *SnapinAssocCreate
	}

	// SnapinAssocUpsert is the "OnConflict" setter.
	SnapinAssocUpsert struct {
		*sql.UpdateSet
	}
)

// SetSnapinID sets the "snapin_id" field.
func (u *SnapinAssocUpsert) SetSnapinID(v uuid.UUID) *SnapinAssocUpsert {
	u.Set(snapinassoc.FieldSnapinID, v)
	return u
}

// UpdateSnapinID sets the "snapin_id" field to the value that was provided on create.
func (u *SnapinAssocUpsert) UpdateSnapinID() *SnapinAssocUpsert {
	u.SetExcluded(snapinassoc.FieldSnapinID)
	return u
}

// SetHostID sets the "host_id" field.
func (u *SnapinAssocUpsert) SetHostID(v uuid.UUID) *SnapinAssocUpsert {
	u.Set(snapinassoc.FieldHostID, v)
	return u
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *SnapinAssocUpsert) UpdateHostID() *SnapinAssocUpsert {
	u.SetExcluded(snapinassoc.FieldHostID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SnapinAssoc.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(snapinassoc.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SnapinAssocUpsertOne) UpdateNewValues() *SnapinAssocUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(snapinassoc.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SnapinAssoc.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SnapinAssocUpsertOne) Ignore() *SnapinAssocUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SnapinAssocUpsertOne) DoNothing() *SnapinAssocUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SnapinAssocCreate.OnConflict
// documentation for more info.
func (u *SnapinAssocUpsertOne) Update(set func(*SnapinAssocUpsert)) *SnapinAssocUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SnapinAssocUpsert{UpdateSet: update})
	}))
	return u
}

// SetSnapinID sets the "snapin_id" field.
func (u *SnapinAssocUpsertOne) SetSnapinID(v uuid.UUID) *SnapinAssocUpsertOne {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.SetSnapinID(v)
	})
}

// UpdateSnapinID sets the "snapin_id" field to the value that was provided on create.
func (u *SnapinAssocUpsertOne) UpdateSnapinID() *SnapinAssocUpsertOne {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.UpdateSnapinID()
	})
}

// SetHostID sets the "host_id" field.
func (u *SnapinAssocUpsertOne) SetHostID(v uuid.UUID) *SnapinAssocUpsertOne {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *SnapinAssocUpsertOne) UpdateHostID() *SnapinAssocUpsertOne {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.UpdateHostID()
	})
}

// Exec executes the query.
func (u *SnapinAssocUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SnapinAssocCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SnapinAssocUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SnapinAssocUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SnapinAssocUpsertOne.ID is not supported by MySQL driver. Use SnapinAssocUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SnapinAssocUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SnapinAssocCreateBulk is the builder for creating many SnapinAssoc entities in bulk.
type SnapinAssocCreateBulk struct {
	config
	err      error
	builders []*SnapinAssocCreate
	conflict []sql.ConflictOption
}

// Save creates the SnapinAssoc entities in the database.
func (_c *SnapinAssocCreateBulk) Save(ctx context.Context) ([]*SnapinAssoc, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SnapinAssoc, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SnapinAssocMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SnapinAssocCreateBulk) SaveX(ctx context.Context) []*SnapinAssoc {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapinAssocCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapinAssocCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SnapinAssoc.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SnapinAssocUpsert) {
//			SetSnapinID(v+v).
//		}).
//		Exec(ctx)
func (_c *SnapinAssocCreateBulk) OnConflict(opts ...sql.ConflictOption) *SnapinAssocUpsertBulk {
	_c.conflict = opts
	return &SnapinAssocUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SnapinAssoc.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SnapinAssocCreateBulk) OnConflictColumns(columns ...string) *SnapinAssocUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SnapinAssocUpsertBulk{
		create: _c,
	}
}

// SnapinAssocUpsertBulk is the builder for "upsert"-ing
// a bulk of SnapinAssoc nodes.
type SnapinAssocUpsertBulk struct {
	create *SnapinAssocCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SnapinAssoc.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(snapinassoc.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SnapinAssocUpsertBulk) UpdateNewValues() *SnapinAssocUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(snapinassoc.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SnapinAssoc.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SnapinAssocUpsertBulk) Ignore() *SnapinAssocUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SnapinAssocUpsertBulk) DoNothing() *SnapinAssocUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SnapinAssocCreateBulk.OnConflict
// documentation for more info.
func (u *SnapinAssocUpsertBulk) Update(set func(*SnapinAssocUpsert)) *SnapinAssocUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SnapinAssocUpsert{UpdateSet: update})
	}))
	return u
}

// SetSnapinID sets the "snapin_id" field.
func (u *SnapinAssocUpsertBulk) SetSnapinID(v uuid.UUID) *SnapinAssocUpsertBulk {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.SetSnapinID(v)
	})
}

// UpdateSnapinID sets the "snapin_id" field to the value that was provided on create.
func (u *SnapinAssocUpsertBulk) UpdateSnapinID() *SnapinAssocUpsertBulk {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.UpdateSnapinID()
	})
}

// SetHostID sets the "host_id" field.
func (u *SnapinAssocUpsertBulk) SetHostID(v uuid.UUID) *SnapinAssocUpsertBulk {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.SetHostID(v)
	})
}

// UpdateHostID sets the "host_id" field to the value that was provided on create.
func (u *SnapinAssocUpsertBulk) UpdateHostID() *SnapinAssocUpsertBulk {
	return u.Update(func(s *SnapinAssocUpsert) {
		s.UpdateHostID()
	})
}

// Exec executes the query.
func (u *SnapinAssocUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SnapinAssocCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SnapinAssocCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SnapinAssocUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
