// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/host"
	"github.com/nemvince/fog-next/ent/snapinjob"
)

// SnapinJob is the model entity for the SnapinJob schema.
type SnapinJob struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// HostID holds the value of the "host_id" field.
	HostID uuid.UUID `json:"hostId"`
	// State holds the value of the "state" field.
	State string `json:"state"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updatedAt"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SnapinJobQuery when eager-loading is set.
	Edges        SnapinJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SnapinJobEdges holds the relations/edges for other nodes in the graph.
type SnapinJobEdges struct {
	// Host holds the value of the host edge.
	Host *Host `json:"host,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*SnapinTask `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	namedTasks  map[string][]*SnapinTask
}

// HostOrErr returns the Host value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SnapinJobEdges) HostOrErr() (*Host, error) {
	if e.Host != nil {
		return e.Host, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: host.Label}
	}
	return nil, &NotLoadedError{edge: "host"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e SnapinJobEdges) TasksOrErr() ([]*SnapinTask, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SnapinJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case snapinjob.FieldState:
			values[i] = new(sql.NullString)
		case snapinjob.FieldCreatedAt, snapinjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case snapinjob.FieldID, snapinjob.FieldHostID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SnapinJob fields.
func (_m *SnapinJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case snapinjob.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case snapinjob.FieldHostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field host_id", values[i])
			} else if value != nil {
				_m.HostID = *value
			}
		case snapinjob.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case snapinjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case snapinjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SnapinJob.
// This includes values selected through modifiers, order, etc.
func (_m *SnapinJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHost queries the "host" edge of the SnapinJob entity.
func (_m *SnapinJob) QueryHost() *HostQuery {
	return NewSnapinJobClient(_m.config).QueryHost(_m)
}

// QueryTasks queries the "tasks" edge of the SnapinJob entity.
func (_m *SnapinJob) QueryTasks() *SnapinTaskQuery {
	return NewSnapinJobClient(_m.config).QueryTasks(_m)
}

// Update returns a builder for updating this SnapinJob.
// Note that you need to call SnapinJob.Unwrap() before calling this method if this SnapinJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SnapinJob) Update() *SnapinJobUpdateOne {
	return NewSnapinJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SnapinJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SnapinJob) Unwrap() *SnapinJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SnapinJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SnapinJob) String() string {
	var builder strings.Builder
	builder.WriteString("SnapinJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("host_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HostID))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedTasks returns the Tasks named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *SnapinJob) NamedTasks(name string) ([]*SnapinTask, error) {
	if _m.Edges.namedTasks == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTasks[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *SnapinJob) appendNamedTasks(name string, edges ...*SnapinTask) {
	if _m.Edges.namedTasks == nil {
		_m.Edges.namedTasks = make(map[string][]*SnapinTask)
	}
	if len(edges) == 0 {
		_m.Edges.namedTasks[name] = []*SnapinTask{}
	} else {
		_m.Edges.namedTasks[name] = append(_m.Edges.namedTasks[name], edges...)
	}
}

// SnapinJobs is a parsable slice of SnapinJob.
type SnapinJobs []*SnapinJob
