// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/snapin"
	"github.com/nemvince/fog-next/ent/snapinassoc"
	"github.com/nemvince/fog-next/ent/snapintask"
)

// SnapinCreate is the builder for creating a Snapin entity.
type SnapinCreate struct {
	config
	mutation *SnapinMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SnapinCreate) SetName(v string) *SnapinCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SnapinCreate) SetDescription(v string) *SnapinCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableDescription(v *string) *SnapinCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *SnapinCreate) SetFileName(v string) *SnapinCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableFileName(v *string) *SnapinCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *SnapinCreate) SetFilePath(v string) *SnapinCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableFilePath(v *string) *SnapinCreate {
	if v != nil {
		_c.SetFilePath(*v)
	}
	return _c
}

// SetCommand sets the "command" field.
func (_c *SnapinCreate) SetCommand(v string) *SnapinCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableCommand(v *string) *SnapinCreate {
	if v != nil {
		_c.SetCommand(*v)
	}
	return _c
}

// SetArguments sets the "arguments" field.
func (_c *SnapinCreate) SetArguments(v string) *SnapinCreate {
	_c.mutation.SetArguments(v)
	return _c
}

// SetNillableArguments sets the "arguments" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableArguments(v *string) *SnapinCreate {
	if v != nil {
		_c.SetArguments(*v)
	}
	return _c
}

// SetRunWith sets the "run_with" field.
func (_c *SnapinCreate) SetRunWith(v string) *SnapinCreate {
	_c.mutation.SetRunWith(v)
	return _c
}

// SetNillableRunWith sets the "run_with" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableRunWith(v *string) *SnapinCreate {
	if v != nil {
		_c.SetRunWith(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *SnapinCreate) SetHash(v string) *SnapinCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableHash(v *string) *SnapinCreate {
	if v != nil {
		_c.SetHash(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *SnapinCreate) SetSizeBytes(v int64) *SnapinCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableSizeBytes(v *int64) *SnapinCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *SnapinCreate) SetIsEnabled(v bool) *SnapinCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableIsEnabled(v *bool) *SnapinCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetToReplicate sets the "to_replicate" field.
func (_c *SnapinCreate) SetToReplicate(v bool) *SnapinCreate {
	_c.mutation.SetToReplicate(v)
	return _c
}

// SetNillableToReplicate sets the "to_replicate" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableToReplicate(v *bool) *SnapinCreate {
	if v != nil {
		_c.SetToReplicate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SnapinCreate) SetCreatedAt(v time.Time) *SnapinCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableCreatedAt(v *time.Time) *SnapinCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SnapinCreate) SetCreatedBy(v string) *SnapinCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableCreatedBy(v *string) *SnapinCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SnapinCreate) SetUpdatedAt(v time.Time) *SnapinCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableUpdatedAt(v *time.Time) *SnapinCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SnapinCreate) SetID(v uuid.UUID) *SnapinCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SnapinCreate) SetNillableID(v *uuid.UUID) *SnapinCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAssocIDs adds the "assocs" edge to the SnapinAssoc entity by IDs.
func (_c *SnapinCreate) AddAssocIDs(ids ...uuid.UUID) *SnapinCreate {
	_c.mutation.AddAssocIDs(ids...)
	return _c
}

// AddAssocs adds the "assocs" edges to the SnapinAssoc entity.
func (_c *SnapinCreate) AddAssocs(v ...*SnapinAssoc) *SnapinCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssocIDs(ids...)
}

// AddSnapinTaskIDs adds the "snapin_tasks" edge to the SnapinTask entity by IDs.
func (_c *SnapinCreate) AddSnapinTaskIDs(ids ...uuid.UUID) *SnapinCreate {
	_c.mutation.AddSnapinTaskIDs(ids...)
	return _c
}

// AddSnapinTasks adds the "snapin_tasks" edges to the SnapinTask entity.
func (_c *SnapinCreate) AddSnapinTasks(v ...*SnapinTask) *SnapinCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSnapinTaskIDs(ids...)
}

// Mutation returns the SnapinMutation object of the builder.
func (_c *SnapinCreate) Mutation() *SnapinMutation {
	return _c.mutation
}

// Save creates the Snapin in the database.
func (_c *SnapinCreate) Save(ctx context.Context) (*Snapin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SnapinCreate) SaveX(ctx context.Context) *Snapin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapinCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapinCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SnapinCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := snapin.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := snapin.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		v := snapin.DefaultFilePath
		_c.mutation.SetFilePath(v)
	}
	if _, ok := _c.mutation.Command(); !ok {
		v := snapin.DefaultCommand
		_c.mutation.SetCommand(v)
	}
	if _, ok := _c.mutation.Arguments(); !ok {
		v := snapin.DefaultArguments
		_c.mutation.SetArguments(v)
	}
	if _, ok := _c.mutation.RunWith(); !ok {
		v := snapin.DefaultRunWith
		_c.mutation.SetRunWith(v)
	}
	if _, ok := _c.mutation.Hash(); !ok {
		v := snapin.DefaultHash
		_c.mutation.SetHash(v)
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := snapin.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := snapin.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.ToReplicate(); !ok {
		v := snapin.DefaultToReplicate
		_c.mutation.SetToReplicate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := snapin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := snapin.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := snapin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := snapin.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SnapinCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Snapin.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := snapin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Snapin.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Snapin.description"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Snapin.file_name"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "Snapin.file_path"`)}
	}
	if _, ok := _c.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "Snapin.command"`)}
	}
	if _, ok := _c.mutation.Arguments(); !ok {
		return &ValidationError{Name: "arguments", err: errors.New(`ent: missing required field "Snapin.arguments"`)}
	}
	if _, ok := _c.mutation.RunWith(); !ok {
		return &ValidationError{Name: "run_with", err: errors.New(`ent: missing required field "Snapin.run_with"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Snapin.hash"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "Snapin.size_bytes"`)}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "Snapin.is_enabled"`)}
	}
	if _, ok := _c.mutation.ToReplicate(); !ok {
		return &ValidationError{Name: "to_replicate", err: errors.New(`ent: missing required field "Snapin.to_replicate"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Snapin.created_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Snapin.created_by"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Snapin.updated_at"`)}
	}
	return nil
}

func (_c *SnapinCreate) sqlSave(ctx context.Context) (*Snapin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SnapinCreate) createSpec() (*Snapin, *sqlgraph.CreateSpec) {
	var (
		_node = &Snapin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(snapin.Table, sqlgraph.NewFieldSpec(snapin.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(snapin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(snapin.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(snapin.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(snapin.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(snapin.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.Arguments(); ok {
		_spec.SetField(snapin.FieldArguments, field.TypeString, value)
		_node.Arguments = value
	}
	if value, ok := _c.mutation.RunWith(); ok {
		_spec.SetField(snapin.FieldRunWith, field.TypeString, value)
		_node.RunWith = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(snapin.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(snapin.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(snapin.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if value, ok := _c.mutation.ToReplicate(); ok {
		_spec.SetField(snapin.FieldToReplicate, field.TypeBool, value)
		_node.ToReplicate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(snapin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(snapin.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(snapin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AssocsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapin.AssocsTable,
			Columns: []string{snapin.AssocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapinassoc.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SnapinTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapin.SnapinTasksTable,
			Columns: []string{snapin.SnapinTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapintask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Snapin.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SnapinUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SnapinCreate) OnConflict(opts ...sql.ConflictOption) *SnapinUpsertOne {
	_c.conflict = opts
	return &SnapinUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Snapin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SnapinCreate) OnConflictColumns(columns ...string) *SnapinUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SnapinUpsertOne{
		create: _c,
	}
}

type (
	// SnapinUpsertOne is the builder for "upsert"-ing
	//  one Snapin node.
	SnapinUpsertOne struct {
		create *SnapinCreate
	}

	// SnapinUpsert is the "OnConflict" setter.
	SnapinUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SnapinUpsert) SetName(v string) *SnapinUpsert {
	u.Set(snapin.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateName() *SnapinUpsert {
	u.SetExcluded(snapin.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SnapinUpsert) SetDescription(v string) *SnapinUpsert {
	u.Set(snapin.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateDescription() *SnapinUpsert {
	u.SetExcluded(snapin.FieldDescription)
	return u
}

// SetFileName sets the "file_name" field.
func (u *SnapinUpsert) SetFileName(v string) *SnapinUpsert {
	u.Set(snapin.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateFileName() *SnapinUpsert {
	u.SetExcluded(snapin.FieldFileName)
	return u
}

// SetFilePath sets the "file_path" field.
func (u *SnapinUpsert) SetFilePath(v string) *SnapinUpsert {
	u.Set(snapin.FieldFilePath, v)
	return u
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateFilePath() *SnapinUpsert {
	u.SetExcluded(snapin.FieldFilePath)
	return u
}

// SetCommand sets the "command" field.
func (u *SnapinUpsert) SetCommand(v string) *SnapinUpsert {
	u.Set(snapin.FieldCommand, v)
	return u
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateCommand() *SnapinUpsert {
	u.SetExcluded(snapin.FieldCommand)
	return u
}

// SetArguments sets the "arguments" field.
func (u *SnapinUpsert) SetArguments(v string) *SnapinUpsert {
	u.Set(snapin.FieldArguments, v)
	return u
}

// UpdateArguments sets the "arguments" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateArguments() *SnapinUpsert {
	u.SetExcluded(snapin.FieldArguments)
	return u
}

// SetRunWith sets the "run_with" field.
func (u *SnapinUpsert) SetRunWith(v string) *SnapinUpsert {
	u.Set(snapin.FieldRunWith, v)
	return u
}

// UpdateRunWith sets the "run_with" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateRunWith() *SnapinUpsert {
	u.SetExcluded(snapin.FieldRunWith)
	return u
}

// SetHash sets the "hash" field.
func (u *SnapinUpsert) SetHash(v string) *SnapinUpsert {
	u.Set(snapin.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateHash() *SnapinUpsert {
	u.SetExcluded(snapin.FieldHash)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SnapinUpsert) SetSizeBytes(v int64) *SnapinUpsert {
	u.Set(snapin.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateSizeBytes() *SnapinUpsert {
	u.SetExcluded(snapin.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SnapinUpsert) AddSizeBytes(v int64) *SnapinUpsert {
	u.Add(snapin.FieldSizeBytes, v)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *SnapinUpsert) SetIsEnabled(v bool) *SnapinUpsert {
	u.Set(snapin.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateIsEnabled() *SnapinUpsert {
	u.SetExcluded(snapin.FieldIsEnabled)
	return u
}

// SetToReplicate sets the "to_replicate" field.
func (u *SnapinUpsert) SetToReplicate(v bool) *SnapinUpsert {
	u.Set(snapin.FieldToReplicate, v)
	return u
}

// UpdateToReplicate sets the "to_replicate" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateToReplicate() *SnapinUpsert {
	u.SetExcluded(snapin.FieldToReplicate)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SnapinUpsert) SetCreatedBy(v string) *SnapinUpsert {
	u.Set(snapin.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateCreatedBy() *SnapinUpsert {
	u.SetExcluded(snapin.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SnapinUpsert) SetUpdatedAt(v time.Time) *SnapinUpsert {
	u.Set(snapin.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SnapinUpsert) UpdateUpdatedAt() *SnapinUpsert {
	u.SetExcluded(snapin.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Snapin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(snapin.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SnapinUpsertOne) UpdateNewValues() *SnapinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(snapin.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(snapin.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Snapin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SnapinUpsertOne) Ignore() *SnapinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SnapinUpsertOne) DoNothing() *SnapinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SnapinCreate.OnConflict
// documentation for more info.
func (u *SnapinUpsertOne) Update(set func(*SnapinUpsert)) *SnapinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SnapinUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SnapinUpsertOne) SetName(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateName() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SnapinUpsertOne) SetDescription(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateDescription() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateDescription()
	})
}

// SetFileName sets the "file_name" field.
func (u *SnapinUpsertOne) SetFileName(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateFileName() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateFileName()
	})
}

// SetFilePath sets the "file_path" field.
func (u *SnapinUpsertOne) SetFilePath(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetFilePath(v)
	})
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateFilePath() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateFilePath()
	})
}

// SetCommand sets the "command" field.
func (u *SnapinUpsertOne) SetCommand(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetCommand(v)
	})
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateCommand() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateCommand()
	})
}

// SetArguments sets the "arguments" field.
func (u *SnapinUpsertOne) SetArguments(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetArguments(v)
	})
}

// UpdateArguments sets the "arguments" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateArguments() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateArguments()
	})
}

// SetRunWith sets the "run_with" field.
func (u *SnapinUpsertOne) SetRunWith(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetRunWith(v)
	})
}

// UpdateRunWith sets the "run_with" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateRunWith() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateRunWith()
	})
}

// SetHash sets the "hash" field.
func (u *SnapinUpsertOne) SetHash(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateHash() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateHash()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SnapinUpsertOne) SetSizeBytes(v int64) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SnapinUpsertOne) AddSizeBytes(v int64) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateSizeBytes() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *SnapinUpsertOne) SetIsEnabled(v bool) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateIsEnabled() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetToReplicate sets the "to_replicate" field.
func (u *SnapinUpsertOne) SetToReplicate(v bool) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetToReplicate(v)
	})
}

// UpdateToReplicate sets the "to_replicate" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateToReplicate() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateToReplicate()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SnapinUpsertOne) SetCreatedBy(v string) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateCreatedBy() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SnapinUpsertOne) SetUpdatedAt(v time.Time) *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SnapinUpsertOne) UpdateUpdatedAt() *SnapinUpsertOne {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SnapinUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SnapinCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SnapinUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SnapinUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SnapinUpsertOne.ID is not supported by MySQL driver. Use SnapinUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SnapinUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SnapinCreateBulk is the builder for creating many Snapin entities in bulk.
type SnapinCreateBulk struct {
	config
	err      error
	builders []*SnapinCreate
	conflict []sql.ConflictOption
}

// Save creates the Snapin entities in the database.
func (_c *SnapinCreateBulk) Save(ctx context.Context) ([]*Snapin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Snapin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SnapinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SnapinCreateBulk) SaveX(ctx context.Context) []*Snapin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapinCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapinCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Snapin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SnapinUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SnapinCreateBulk) OnConflict(opts ...sql.ConflictOption) *SnapinUpsertBulk {
	_c.conflict = opts
	return &SnapinUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Snapin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SnapinCreateBulk) OnConflictColumns(columns ...string) *SnapinUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SnapinUpsertBulk{
		create: _c,
	}
}

// SnapinUpsertBulk is the builder for "upsert"-ing
// a bulk of Snapin nodes.
type SnapinUpsertBulk struct {
	create *SnapinCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Snapin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(snapin.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SnapinUpsertBulk) UpdateNewValues() *SnapinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(snapin.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(snapin.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Snapin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SnapinUpsertBulk) Ignore() *SnapinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SnapinUpsertBulk) DoNothing() *SnapinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SnapinCreateBulk.OnConflict
// documentation for more info.
func (u *SnapinUpsertBulk) Update(set func(*SnapinUpsert)) *SnapinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SnapinUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SnapinUpsertBulk) SetName(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateName() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SnapinUpsertBulk) SetDescription(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateDescription() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateDescription()
	})
}

// SetFileName sets the "file_name" field.
func (u *SnapinUpsertBulk) SetFileName(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateFileName() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateFileName()
	})
}

// SetFilePath sets the "file_path" field.
func (u *SnapinUpsertBulk) SetFilePath(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetFilePath(v)
	})
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateFilePath() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateFilePath()
	})
}

// SetCommand sets the "command" field.
func (u *SnapinUpsertBulk) SetCommand(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetCommand(v)
	})
}

// UpdateCommand sets the "command" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateCommand() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateCommand()
	})
}

// SetArguments sets the "arguments" field.
func (u *SnapinUpsertBulk) SetArguments(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetArguments(v)
	})
}

// UpdateArguments sets the "arguments" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateArguments() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateArguments()
	})
}

// SetRunWith sets the "run_with" field.
func (u *SnapinUpsertBulk) SetRunWith(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetRunWith(v)
	})
}

// UpdateRunWith sets the "run_with" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateRunWith() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateRunWith()
	})
}

// SetHash sets the "hash" field.
func (u *SnapinUpsertBulk) SetHash(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateHash() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateHash()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *SnapinUpsertBulk) SetSizeBytes(v int64) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *SnapinUpsertBulk) AddSizeBytes(v int64) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateSizeBytes() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *SnapinUpsertBulk) SetIsEnabled(v bool) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateIsEnabled() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetToReplicate sets the "to_replicate" field.
func (u *SnapinUpsertBulk) SetToReplicate(v bool) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetToReplicate(v)
	})
}

// UpdateToReplicate sets the "to_replicate" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateToReplicate() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateToReplicate()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SnapinUpsertBulk) SetCreatedBy(v string) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateCreatedBy() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SnapinUpsertBulk) SetUpdatedAt(v time.Time) *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SnapinUpsertBulk) UpdateUpdatedAt() *SnapinUpsertBulk {
	return u.Update(func(s *SnapinUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SnapinUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SnapinCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SnapinCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SnapinUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
