// Code generated by ent, DO NOT EDIT.

package multicastsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/nemvince/fog-next/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldName, v))
}

// ImageID applies equality check predicate on the "image_id" field. It's identical to ImageIDEQ.
func ImageID(v uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldImageID, v))
}

// StorageNodeID applies equality check predicate on the "storage_node_id" field. It's identical to StorageNodeIDEQ.
func StorageNodeID(v uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldStorageNodeID, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldPort, v))
}

// Interface applies equality check predicate on the "interface" field. It's identical to InterfaceEQ.
func Interface(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldInterface, v))
}

// ClientCount applies equality check predicate on the "client_count" field. It's identical to ClientCountEQ.
func ClientCount(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldClientCount, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldState, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldContainsFold(FieldName, v))
}

// ImageIDEQ applies the EQ predicate on the "image_id" field.
func ImageIDEQ(v uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldImageID, v))
}

// ImageIDNEQ applies the NEQ predicate on the "image_id" field.
func ImageIDNEQ(v uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldImageID, v))
}

// ImageIDIn applies the In predicate on the "image_id" field.
func ImageIDIn(vs ...uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldImageID, vs...))
}

// ImageIDNotIn applies the NotIn predicate on the "image_id" field.
func ImageIDNotIn(vs ...uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldImageID, vs...))
}

// StorageNodeIDEQ applies the EQ predicate on the "storage_node_id" field.
func StorageNodeIDEQ(v uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldStorageNodeID, v))
}

// StorageNodeIDNEQ applies the NEQ predicate on the "storage_node_id" field.
func StorageNodeIDNEQ(v uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldStorageNodeID, v))
}

// StorageNodeIDIn applies the In predicate on the "storage_node_id" field.
func StorageNodeIDIn(vs ...uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldStorageNodeID, vs...))
}

// StorageNodeIDNotIn applies the NotIn predicate on the "storage_node_id" field.
func StorageNodeIDNotIn(vs ...uuid.UUID) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldStorageNodeID, vs...))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldPort, v))
}

// InterfaceEQ applies the EQ predicate on the "interface" field.
func InterfaceEQ(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldInterface, v))
}

// InterfaceNEQ applies the NEQ predicate on the "interface" field.
func InterfaceNEQ(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldInterface, v))
}

// InterfaceIn applies the In predicate on the "interface" field.
func InterfaceIn(vs ...string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldInterface, vs...))
}

// InterfaceNotIn applies the NotIn predicate on the "interface" field.
func InterfaceNotIn(vs ...string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldInterface, vs...))
}

// InterfaceGT applies the GT predicate on the "interface" field.
func InterfaceGT(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldInterface, v))
}

// InterfaceGTE applies the GTE predicate on the "interface" field.
func InterfaceGTE(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldInterface, v))
}

// InterfaceLT applies the LT predicate on the "interface" field.
func InterfaceLT(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldInterface, v))
}

// InterfaceLTE applies the LTE predicate on the "interface" field.
func InterfaceLTE(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldInterface, v))
}

// InterfaceContains applies the Contains predicate on the "interface" field.
func InterfaceContains(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldContains(FieldInterface, v))
}

// InterfaceHasPrefix applies the HasPrefix predicate on the "interface" field.
func InterfaceHasPrefix(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldHasPrefix(FieldInterface, v))
}

// InterfaceHasSuffix applies the HasSuffix predicate on the "interface" field.
func InterfaceHasSuffix(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldHasSuffix(FieldInterface, v))
}

// InterfaceEqualFold applies the EqualFold predicate on the "interface" field.
func InterfaceEqualFold(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEqualFold(FieldInterface, v))
}

// InterfaceContainsFold applies the ContainsFold predicate on the "interface" field.
func InterfaceContainsFold(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldContainsFold(FieldInterface, v))
}

// ClientCountEQ applies the EQ predicate on the "client_count" field.
func ClientCountEQ(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldClientCount, v))
}

// ClientCountNEQ applies the NEQ predicate on the "client_count" field.
func ClientCountNEQ(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldClientCount, v))
}

// ClientCountIn applies the In predicate on the "client_count" field.
func ClientCountIn(vs ...int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldClientCount, vs...))
}

// ClientCountNotIn applies the NotIn predicate on the "client_count" field.
func ClientCountNotIn(vs ...int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldClientCount, vs...))
}

// ClientCountGT applies the GT predicate on the "client_count" field.
func ClientCountGT(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldClientCount, v))
}

// ClientCountGTE applies the GTE predicate on the "client_count" field.
func ClientCountGTE(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldClientCount, v))
}

// ClientCountLT applies the LT predicate on the "client_count" field.
func ClientCountLT(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldClientCount, v))
}

// ClientCountLTE applies the LTE predicate on the "client_count" field.
func ClientCountLTE(v int) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldClientCount, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldContainsFold(FieldState, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MulticastSession {
	return predicate.MulticastSession(sql.FieldLTE(FieldCreatedAt, v))
}

// HasImage applies the HasEdge predicate on the "image" edge.
func HasImage() predicate.MulticastSession {
	return predicate.MulticastSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ImageTable, ImageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImageWith applies the HasEdge predicate on the "image" edge with a given conditions (other predicates).
func HasImageWith(preds ...predicate.Image) predicate.MulticastSession {
	return predicate.MulticastSession(func(s *sql.Selector) {
		step := newImageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStorageNode applies the HasEdge predicate on the "storage_node" edge.
func HasStorageNode() predicate.MulticastSession {
	return predicate.MulticastSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StorageNodeTable, StorageNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStorageNodeWith applies the HasEdge predicate on the "storage_node" edge with a given conditions (other predicates).
func HasStorageNodeWith(preds ...predicate.StorageNode) predicate.MulticastSession {
	return predicate.MulticastSession(func(s *sql.Selector) {
		step := newStorageNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MulticastSession) predicate.MulticastSession {
	return predicate.MulticastSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MulticastSession) predicate.MulticastSession {
	return predicate.MulticastSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MulticastSession) predicate.MulticastSession {
	return predicate.MulticastSession(sql.NotPredicates(p))
}
